import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
// waas v1-26.6.17-061733f 2279592e720c50a33130cd3fd935b3e2e74ff67d
//
// Code generated by webrpc-gen@v0.37.2 with github.com/webrpc/gen-swift@v0.1.2 generator. DO NOT EDIT.
//
// webrpc-gen -schema=schema/waas.ridl -target=github.com/webrpc/gen-swift@v0.1.2 -client -out=./clients/waas.gen.swift

package let WEBRPC_VERSION = "v1"
package let WEBRPC_SCHEMA_VERSION = "v1-26.6.17-061733f"
package let WEBRPC_SCHEMA_HASH = "2279592e720c50a33130cd3fd935b3e2e74ff67d"

package let WEBRPC_HEADER = "Webrpc"
package let WEBRPC_HEADER_VALUE = "webrpc@v0.37.2;gen-swift@v0.1.2;waas@v1-26.6.17-061733f"

package struct WebRPCGeneratedVersions: Sendable, Equatable {
    package let webrpcGenVersion: String
    package let codeGenName: String
    package let codeGenVersion: String
    package let schemaName: String
    package let schemaVersion: String

    package init(
        webrpcGenVersion: String = "",
        codeGenName: String = "",
        codeGenVersion: String = "",
        schemaName: String = "",
        schemaVersion: String = ""
    ) {
        self.webrpcGenVersion = webrpcGenVersion
        self.codeGenName = codeGenName
        self.codeGenVersion = codeGenVersion
        self.schemaName = schemaName
        self.schemaVersion = schemaVersion
    }

    package static let empty = WebRPCGeneratedVersions()
}

package func versionFromHeader(_ headers: [String: String]) -> WebRPCGeneratedVersions {
    guard let headerValue = webRPCHeaderValue(in: headers) else {
        return .empty
    }
    return parseWebRPCGeneratedVersions(headerValue)
}

package func versionFromHeader(_ response: WebRPCHTTPResponse) -> WebRPCGeneratedVersions {
    versionFromHeader(response.headers)
}

private func webRPCHeaderValue(in headers: [String: String]) -> String? {
    for (name, value) in headers {
        if name.caseInsensitiveCompare(WEBRPC_HEADER) == .orderedSame {
            return value
        }
    }
    return nil
}

private func parseWebRPCGeneratedVersions(_ header: String) -> WebRPCGeneratedVersions {
    let versions = header.split(separator: ";", omittingEmptySubsequences: false)
    guard versions.count >= 3 else {
        return .empty
    }

    let webrpcParts = versions[0].split(separator: "@", maxSplits: 1, omittingEmptySubsequences: false)
    let codeGenParts = versions[1].split(separator: "@", maxSplits: 1, omittingEmptySubsequences: false)
    let schemaParts = versions[2].split(separator: "@", maxSplits: 1, omittingEmptySubsequences: false)

    return WebRPCGeneratedVersions(
        webrpcGenVersion: webrpcParts.count > 1 ? String(webrpcParts[1]) : "",
        codeGenName: codeGenParts.count > 0 ? String(codeGenParts[0]) : "",
        codeGenVersion: codeGenParts.count > 1 ? String(codeGenParts[1]) : "",
        schemaName: schemaParts.count > 0 ? String(schemaParts[0]) : "",
        schemaVersion: schemaParts.count > 1 ? String(schemaParts[1]) : ""
    )
}

private func makeWebRPCHeaders(
    _ headers: [String: String],
    includeWebRPCHeader: Bool
) -> [String: String] {
    var requestHeaders = headers
    if includeWebRPCHeader {
        requestHeaders[WEBRPC_HEADER] = WEBRPC_HEADER_VALUE
    }
    return requestHeaders
}

package enum WebRPCJSON {
    package static func makeEncoder() -> JSONEncoder {
        JSONEncoder()
    }

    package static func makeDecoder() -> JSONDecoder {
        JSONDecoder()
    }
}

package struct WebRPCNull: Codable, Sendable {
    package init() {}

    package init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        guard container.decodeNil() else {
            throw DecodingError.typeMismatch(
                WebRPCNull.self,
                DecodingError.Context(
                    codingPath: decoder.codingPath,
                    debugDescription: "Expected null",
                ),
            )
        }
    }

    package func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encodeNil()
    }
}

package enum WebRPCJSONValue: Codable, Sendable {
    case object([String: WebRPCJSONValue])
    case array([WebRPCJSONValue])
    case string(String)
    case integer(Int64)
    case unsignedInteger(UInt64)
    case number(Double)
    case bool(Bool)
    case null

    package init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()

        if container.decodeNil() {
            self = .null
        } else if let value = try? container.decode(Bool.self) {
            self = .bool(value)
        } else if let value = try? container.decode(Int64.self) {
            self = .integer(value)
        } else if let value = try? container.decode(UInt64.self) {
            self = .unsignedInteger(value)
        } else if let value = try? container.decode(Double.self) {
            self = .number(value)
        } else if let value = try? container.decode(String.self) {
            self = .string(value)
        } else if let value = try? container.decode([WebRPCJSONValue].self) {
            self = .array(value)
        } else if let value = try? container.decode([String: WebRPCJSONValue].self) {
            self = .object(value)
        } else {
            throw DecodingError.dataCorruptedError(
                in: container,
                debugDescription: "Unsupported JSON value",
            )
        }
    }

    package func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()

        switch self {
        case .object(let value):
            try container.encode(value)
        case .array(let value):
            try container.encode(value)
        case .string(let value):
            try container.encode(value)
        case .integer(let value):
            try container.encode(value)
        case .unsignedInteger(let value):
            try container.encode(value)
        case .number(let value):
            try container.encode(value)
        case .bool(let value):
            try container.encode(value)
        case .null:
            try container.encodeNil()
        }
    }
}

package protocol WebRPCEnumKey: Hashable, Sendable {
    init(wireValue: String)
    var wireValue: String { get }
}

package struct WebRPCEnumMap<Key, Value>: Codable, Sendable
where Key: WebRPCEnumKey, Value: Codable & Sendable {
    package var values: [Key: Value]

    package init(_ values: [Key: Value] = [:]) {
        self.values = values
    }

    package init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let rawValues = try container.decode([String: Value].self)

        var values: [Key: Value] = [:]
        values.reserveCapacity(rawValues.count)

        for (key, value) in rawValues {
            values[Key(wireValue: key)] = value
        }

        self.values = values
    }

    package func encode(to encoder: Encoder) throws {
        let rawValues = Dictionary(uniqueKeysWithValues: values.map { ($0.key.wireValue, $0.value) })
        var container = encoder.singleValueContainer()
        try container.encode(rawValues)
    }
}

package struct WebRPCHTTPResponse: Sendable {
    package let statusCode: Int
    package let body: Data
    package let headers: [String: String]

    package init(
        statusCode: Int,
        body: Data,
        headers: [String: String] = [:]
    ) {
        self.statusCode = statusCode
        self.body = body
        self.headers = headers
    }
}

package protocol WebRPCTransport: Sendable {
    func post(
        baseURL: String,
        path: String,
        body: Data,
        headers: [String: String]
    ) async throws -> WebRPCHTTPResponse
}

package struct WebRPCTransportError: Error, Sendable {
    package let message: String
    package let underlyingDescription: String?

    package init(message: String, underlyingDescription: String? = nil) {
        self.message = message
        self.underlyingDescription = underlyingDescription
    }
}

package struct URLSessionWebRPCTransport: WebRPCTransport, @unchecked Sendable {
    package let session: URLSession

    package init(session: URLSession = .shared) {
        self.session = session
    }

    package func post(
        baseURL: String,
        path: String,
        body: Data,
        headers: [String: String]
    ) async throws -> WebRPCHTTPResponse {
        guard let url = URL(string: joinWebRPCURL(baseURL: baseURL, path: path)) else {
            throw WebRPCTransportError(message: "Invalid WebRPC URL")
        }

        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.httpBody = body
        request.setValue("application/json; charset=utf-8", forHTTPHeaderField: "Content-Type")

        for (name, value) in headers {
            request.setValue(value, forHTTPHeaderField: name)
        }

        do {
            let (data, response) = try await session.data(for: request)
            let httpResponse = response as? HTTPURLResponse
            let responseHeaders = (httpResponse?.allHeaderFields ?? [:]).reduce(into: [String: String]()) { result, item in
                guard let key = item.key as? String else {
                    return
                }
                result[key] = String(describing: item.value)
            }

            return WebRPCHTTPResponse(
                statusCode: httpResponse?.statusCode ?? 0,
                body: data,
                headers: responseHeaders,
            )
        } catch is CancellationError {
            throw CancellationError()
        } catch {
            throw WebRPCTransportError(
                message: "WebRPC HTTP request failed",
                underlyingDescription: String(describing: error),
            )
        }
    }
}

private func joinWebRPCURL(baseURL: String, path: String) -> String {
    baseURL.trimmingCharacters(in: CharacterSet(charactersIn: "/")) + "/" + path.trimmingCharacters(in: CharacterSet(charactersIn: "/"))
}

package func executeWebRPC<Response>(
    baseURL: String,
    urlPath: String,
    body: Data,
    transport: any WebRPCTransport,
    headers: [String: String] = [:],
    decodeSuccess: (Data, JSONDecoder) throws -> Response
) async throws -> Response {
    let response: WebRPCHTTPResponse
    do {
        response = try await transport.post(
            baseURL: baseURL,
            path: urlPath,
            body: body,
            headers: headers,
        )
    } catch is CancellationError {
        throw CancellationError()
    } catch let error as WebRPCTransportError {
        throw error
    } catch {
        throw WebRPCTransportError(
            message: "WebRPC request failed",
            underlyingDescription: String(describing: error),
        )
    }

    guard (200...299).contains(response.statusCode) else {
        throw decodeWebRPCError(statusCode: response.statusCode, data: response.body)
    }

    do {
        return try decodeSuccess(response.body, WebRPCJSON.makeDecoder())
    } catch let error as WebRPCError {
        throw error
    } catch {
        throw webRPCBadResponseError(
            statusCode: response.statusCode,
            data: response.body,
            cause: String(describing: error)
        )
    }
}

package enum WebRPCErrorKind: Sendable {
    case webrpcEndpoint
    case webrpcRequestFailed
    case webrpcBadRoute
    case webrpcBadMethod
    case webrpcBadRequest
    case webrpcBadResponse
    case webrpcServerPanic
    case webrpcInternalError
    case webrpcClientAborted
    case webrpcStreamLost
    case webrpcStreamFinished
    case internalError
    case encryptionError
    case databaseError
    case dataIntegrityError
    case identityProviderError
    case invalidRequest
    case invalidSignature
    case keyNotFound
    case keyExpired
    case signerNotFound
    case usageLimitExceeded
    case preconditionFailed
    case unauthorized
    case proofVerificationFailed
    case answerIncorrect
    case challengeExpired
    case tooManyAttempts
    case commitmentConsumed
    case oauthError
    case accessError
    case authMethodUnavailable
    case otpRateLimited
    case walletNotFound
    case accountNotFound
    case accountAlreadyExists
    case unsupportedWalletType
    case unsupportedNetwork
    case unsupportedTransactionMode
    case transactionFailed
    case walletProviderError
    case transactionNotFound
    case transactionExpired
    case invalidFeeOption
    case transactionBroadcastFailed
    case unknown

    package var code: Int {
        switch self {
        case .webrpcEndpoint:
            return 0
        case .webrpcRequestFailed:
            return -1
        case .webrpcBadRoute:
            return -2
        case .webrpcBadMethod:
            return -3
        case .webrpcBadRequest:
            return -4
        case .webrpcBadResponse:
            return -5
        case .webrpcServerPanic:
            return -6
        case .webrpcInternalError:
            return -7
        case .webrpcClientAborted:
            return -8
        case .webrpcStreamLost:
            return -9
        case .webrpcStreamFinished:
            return -10
        case .internalError:
            return 7100
        case .encryptionError:
            return 7101
        case .databaseError:
            return 7102
        case .dataIntegrityError:
            return 7103
        case .identityProviderError:
            return 7104
        case .invalidRequest:
            return 7200
        case .invalidSignature:
            return 7201
        case .keyNotFound:
            return 7202
        case .keyExpired:
            return 7203
        case .signerNotFound:
            return 7204
        case .usageLimitExceeded:
            return 7205
        case .preconditionFailed:
            return 7206
        case .unauthorized:
            return 7207
        case .proofVerificationFailed:
            return 7002
        case .answerIncorrect:
            return 7003
        case .challengeExpired:
            return 7004
        case .tooManyAttempts:
            return 7005
        case .commitmentConsumed:
            return 7008
        case .oauthError:
            return 7006
        case .accessError:
            return 7007
        case .authMethodUnavailable:
            return 7009
        case .otpRateLimited:
            return 7010
        case .walletNotFound:
            return 7300
        case .accountNotFound:
            return 7301
        case .accountAlreadyExists:
            return 7302
        case .unsupportedWalletType:
            return 7303
        case .unsupportedNetwork:
            return 7304
        case .unsupportedTransactionMode:
            return 7305
        case .transactionFailed:
            return 7306
        case .walletProviderError:
            return 7307
        case .transactionNotFound:
            return 7308
        case .transactionExpired:
            return 7309
        case .invalidFeeOption:
            return 7310
        case .transactionBroadcastFailed:
            return 7311
        case .unknown:
            return -999
        }
    }

    package static func fromCode(_ code: Int) -> WebRPCErrorKind {
        switch code {
        case 0:
            return .webrpcEndpoint
        case -1:
            return .webrpcRequestFailed
        case -2:
            return .webrpcBadRoute
        case -3:
            return .webrpcBadMethod
        case -4:
            return .webrpcBadRequest
        case -5:
            return .webrpcBadResponse
        case -6:
            return .webrpcServerPanic
        case -7:
            return .webrpcInternalError
        case -8:
            return .webrpcClientAborted
        case -9:
            return .webrpcStreamLost
        case -10:
            return .webrpcStreamFinished
        case 7100:
            return .internalError
        case 7101:
            return .encryptionError
        case 7102:
            return .databaseError
        case 7103:
            return .dataIntegrityError
        case 7104:
            return .identityProviderError
        case 7200:
            return .invalidRequest
        case 7201:
            return .invalidSignature
        case 7202:
            return .keyNotFound
        case 7203:
            return .keyExpired
        case 7204:
            return .signerNotFound
        case 7205:
            return .usageLimitExceeded
        case 7206:
            return .preconditionFailed
        case 7207:
            return .unauthorized
        case 7002:
            return .proofVerificationFailed
        case 7003:
            return .answerIncorrect
        case 7004:
            return .challengeExpired
        case 7005:
            return .tooManyAttempts
        case 7008:
            return .commitmentConsumed
        case 7006:
            return .oauthError
        case 7007:
            return .accessError
        case 7009:
            return .authMethodUnavailable
        case 7010:
            return .otpRateLimited
        case 7300:
            return .walletNotFound
        case 7301:
            return .accountNotFound
        case 7302:
            return .accountAlreadyExists
        case 7303:
            return .unsupportedWalletType
        case 7304:
            return .unsupportedNetwork
        case 7305:
            return .unsupportedTransactionMode
        case 7306:
            return .transactionFailed
        case 7307:
            return .walletProviderError
        case 7308:
            return .transactionNotFound
        case 7309:
            return .transactionExpired
        case 7310:
            return .invalidFeeOption
        case 7311:
            return .transactionBroadcastFailed
        default:
            return .unknown
        }
    }
}

package struct WebRPCError: Error, Sendable {
    package let error: String
    package let code: Int
    package let message: String
    package let cause: String
    package let status: Int
    package let kind: WebRPCErrorKind

    package init(
        error: String,
        code: Int,
        message: String,
        cause: String,
        status: Int,
        kind: WebRPCErrorKind
    ) {
        self.error = error
        self.code = code
        self.message = message
        self.cause = cause
        self.status = status
        self.kind = kind
    }
}

private struct WebRPCErrorPayload: Decodable, Sendable {
    let error: String?
    let code: Int?
    let msg: String?
    let cause: String?
    let status: Int?
}

package func decodeWebRPCError(
    statusCode: Int,
    data: Data,
    decoder: JSONDecoder = WebRPCJSON.makeDecoder()
) -> WebRPCError {
    do {
        let payload = try decoder.decode(WebRPCErrorPayload.self, from: data)
        let code = payload.code ?? WebRPCErrorKind.unknown.code
        return WebRPCError(
            error: payload.error ?? "WebrpcEndpoint",
            code: code,
            message: payload.msg ?? "endpoint error",
            cause: payload.cause ?? "",
            status: payload.status ?? statusCode,
            kind: WebRPCErrorKind.fromCode(code),
        )
    } catch {
        return webRPCBadResponseError(
            statusCode: statusCode,
            data: data,
            cause: "Unable to decode error response"
        )
    }
}

private func webRPCBadResponseError(
    statusCode: Int,
    data: Data,
    cause: String
) -> WebRPCError {
    let bodyText = String(data: data, encoding: .utf8) ?? "<non-utf8 body>"
    return WebRPCError(
        error: "WebrpcBadResponse",
        code: WebRPCErrorKind.webrpcBadResponse.code,
        message: "bad response",
        cause: "\(cause): \(bodyText)",
        status: statusCode,
        kind: .webrpcBadResponse
    )
}



// MARK: - Types
package enum WalletType: Codable, Hashable, Sendable, WebRPCEnumKey {
    case ethereum
    case unknown(String)

    package var wireValue: String {
        switch self {
        case .ethereum:
            return "ethereum"
        case .unknown(let value):
            return value
        }
    }

    package init(wireValue: String) {
        switch wireValue {
        case "ethereum":
            self = .ethereum
        default:
            self = .unknown(wireValue)
        }
    }

    package init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let value = try container.decode(String.self)
        self = WalletType(wireValue: value)
    }

    package func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(wireValue)
    }
}


package enum WalletStatus: Codable, Hashable, Sendable, WebRPCEnumKey {
    case active
    case suspended
    case unknown(String)

    package var wireValue: String {
        switch self {
        case .active:
            return "active"
        case .suspended:
            return "suspended"
        case .unknown(let value):
            return value
        }
    }

    package init(wireValue: String) {
        switch wireValue {
        case "active":
            self = .active
        case "suspended":
            self = .suspended
        default:
            self = .unknown(wireValue)
        }
    }

    package init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let value = try container.decode(String.self)
        self = WalletStatus(wireValue: value)
    }

    package func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(wireValue)
    }
}


package enum TransactionMode: Codable, Hashable, Sendable, WebRPCEnumKey {
    case native
    case relayer
    case unknown(String)

    package var wireValue: String {
        switch self {
        case .native:
            return "native"
        case .relayer:
            return "relayer"
        case .unknown(let value):
            return value
        }
    }

    package init(wireValue: String) {
        switch wireValue {
        case "native":
            self = .native
        case "relayer":
            self = .relayer
        default:
            self = .unknown(wireValue)
        }
    }

    package init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let value = try container.decode(String.self)
        self = TransactionMode(wireValue: value)
    }

    package func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(wireValue)
    }
}


package enum KeyOrigin: Codable, Hashable, Sendable, WebRPCEnumKey {
    case enclave
    case imported
    case unknown(String)

    package var wireValue: String {
        switch self {
        case .enclave:
            return "enclave"
        case .imported:
            return "imported"
        case .unknown(let value):
            return value
        }
    }

    package init(wireValue: String) {
        switch wireValue {
        case "enclave":
            self = .enclave
        case "imported":
            self = .imported
        default:
            self = .unknown(wireValue)
        }
    }

    package init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let value = try container.decode(String.self)
        self = KeyOrigin(wireValue: value)
    }

    package func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(wireValue)
    }
}


package enum IdentityType: Codable, Hashable, Sendable, WebRPCEnumKey {
    case email
    case phone
    case oidc
    case passkey
    case unknown(String)

    package var wireValue: String {
        switch self {
        case .email:
            return "email"
        case .phone:
            return "phone"
        case .oidc:
            return "oidc"
        case .passkey:
            return "passkey"
        case .unknown(let value):
            return value
        }
    }

    package init(wireValue: String) {
        switch wireValue {
        case "email":
            self = .email
        case "phone":
            self = .phone
        case "oidc":
            self = .oidc
        case "passkey":
            self = .passkey
        default:
            self = .unknown(wireValue)
        }
    }

    package init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let value = try container.decode(String.self)
        self = IdentityType(wireValue: value)
    }

    package func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(wireValue)
    }
}


package enum AuthMode: Codable, Hashable, Sendable, WebRPCEnumKey {
    case otp
    case idToken
    case authCode
    case authCodePkce
    case unknown(String)

    package var wireValue: String {
        switch self {
        case .otp:
            return "otp"
        case .idToken:
            return "id-token"
        case .authCode:
            return "auth-code"
        case .authCodePkce:
            return "auth-code-pkce"
        case .unknown(let value):
            return value
        }
    }

    package init(wireValue: String) {
        switch wireValue {
        case "otp":
            self = .otp
        case "id-token":
            self = .idToken
        case "auth-code":
            self = .authCode
        case "auth-code-pkce":
            self = .authCodePkce
        default:
            self = .unknown(wireValue)
        }
    }

    package init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let value = try container.decode(String.self)
        self = AuthMode(wireValue: value)
    }

    package func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(wireValue)
    }
}


package enum SigningAlgorithm: Codable, Hashable, Sendable, WebRPCEnumKey {
    case ecdsaP256Sha256
    case ecdsaP256kEip191
    case unknown(String)

    package var wireValue: String {
        switch self {
        case .ecdsaP256Sha256:
            return "ecdsa-p256-sha256"
        case .ecdsaP256kEip191:
            return "ecdsa-p256k-eip191"
        case .unknown(let value):
            return value
        }
    }

    package init(wireValue: String) {
        switch wireValue {
        case "ecdsa-p256-sha256":
            self = .ecdsaP256Sha256
        case "ecdsa-p256k-eip191":
            self = .ecdsaP256kEip191
        default:
            self = .unknown(wireValue)
        }
    }

    package init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let value = try container.decode(String.self)
        self = SigningAlgorithm(wireValue: value)
    }

    package func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(wireValue)
    }
}


package enum TransactionStatus: Codable, Hashable, Sendable, WebRPCEnumKey {
    case quoted
    case pending
    case executed
    case failed
    case unknown(String)

    package var wireValue: String {
        switch self {
        case .quoted:
            return "quoted"
        case .pending:
            return "pending"
        case .executed:
            return "executed"
        case .failed:
            return "failed"
        case .unknown(let value):
            return value
        }
    }

    package init(wireValue: String) {
        switch wireValue {
        case "quoted":
            self = .quoted
        case "pending":
            self = .pending
        case "executed":
            self = .executed
        case "failed":
            self = .failed
        default:
            self = .unknown(wireValue)
        }
    }

    package init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let value = try container.decode(String.self)
        self = TransactionStatus(wireValue: value)
    }

    package func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(wireValue)
    }
}



package struct Identity: Codable, Sendable {
    package let type: IdentityType
    package let iss: String?
    package let sub: String

    package init(type: IdentityType, iss: String? = nil, sub: String
    ) {
        self.type = type
        self.iss = iss
        self.sub = sub
    }
    enum CodingKeys: String, CodingKey {
        case type = "type"
        case iss = "iss"
        case sub = "sub"
    }
}



package struct IdentityExtras: Codable, Sendable {
    package let email: String?
    package let phone: String?
    package let emailVerified: Bool?

    package init(email: String? = nil, phone: String? = nil, emailVerified: Bool? = nil
    ) {
        self.email = email
        self.phone = phone
        self.emailVerified = emailVerified
    }
    enum CodingKeys: String, CodingKey {
        case email = "email"
        case phone = "phone"
        case emailVerified = "emailVerified"
    }
}



package struct Wallet: Codable, Sendable {
    package let id: String
    package let type: WalletType
    package let address: String
    package let reference: String?

    package init(id: String, type: WalletType, address: String, reference: String? = nil
    ) {
        self.id = id
        self.type = type
        self.address = address
        self.reference = reference
    }
    enum CodingKeys: String, CodingKey {
        case id = "id"
        case type = "type"
        case address = "address"
        case reference = "reference"
    }
}



package struct AuthID: Codable, Sendable {
    package let scope: String
    package let authMode: AuthMode
    package let identityType: IdentityType
    package let verifier: String

    package init(scope: String, authMode: AuthMode, identityType: IdentityType, verifier: String
    ) {
        self.scope = scope
        self.authMode = authMode
        self.identityType = identityType
        self.verifier = verifier
    }
    enum CodingKeys: String, CodingKey {
        case scope = "scope"
        case authMode = "authMode"
        case identityType = "identityType"
        case verifier = "verifier"
    }
}



package struct FeeToken: Codable, Sendable {
    package let network: String
    package let name: String
    package let symbol: String
    package let type: String
    package let decimals: UInt32?
    package let logoUrl: String?
    package let contractAddress: String?
    package let tokenId: String?

    package init(network: String, name: String, symbol: String, type: String, decimals: UInt32? = nil, logoUrl: String? = nil, contractAddress: String? = nil, tokenId: String? = nil
    ) {
        self.network = network
        self.name = name
        self.symbol = symbol
        self.type = type
        self.decimals = decimals
        self.logoUrl = logoUrl
        self.contractAddress = contractAddress
        self.tokenId = tokenId
    }
    enum CodingKeys: String, CodingKey {
        case network = "network"
        case name = "name"
        case symbol = "symbol"
        case type = "type"
        case decimals = "decimals"
        case logoUrl = "logoURL"
        case contractAddress = "contractAddress"
        case tokenId = "tokenID"
    }
}



package struct FeeOption: Codable, Sendable {
    package let token: FeeToken
    package let value: String
    package let displayValue: String

    package init(token: FeeToken, value: String, displayValue: String
    ) {
        self.token = token
        self.value = value
        self.displayValue = displayValue
    }
    enum CodingKeys: String, CodingKey {
        case token = "token"
        case value = "value"
        case displayValue = "displayValue"
    }
}



package struct FeeOptionSelection: Codable, Sendable {
    package let token: String

    package init(token: String
    ) {
        self.token = token
    }
    enum CodingKeys: String, CodingKey {
        case token = "token"
    }
}



package struct Page: Codable, Sendable {
    package let limit: UInt32?
    package let cursor: String?

    package init(limit: UInt32? = nil, cursor: String? = nil
    ) {
        self.limit = limit
        self.cursor = cursor
    }
    enum CodingKeys: String, CodingKey {
        case limit = "limit"
        case cursor = "cursor"
    }
}



package struct CommitVerifierRequest: Codable, Sendable {
    package let identityType: IdentityType
    package let authMode: AuthMode
    package let metadata: [String: String]
    package let handle: String?

    package init(identityType: IdentityType, authMode: AuthMode, metadata: [String: String], handle: String? = nil
    ) {
        self.identityType = identityType
        self.authMode = authMode
        self.metadata = metadata
        self.handle = handle
    }
    enum CodingKeys: String, CodingKey {
        case identityType = "identityType"
        case authMode = "authMode"
        case metadata = "metadata"
        case handle = "handle"
    }
}



package struct CommitVerifierResponse: Codable, Sendable {
    package let verifier: String
    package let loginHint: String?
    package let challenge: String

    package init(verifier: String, loginHint: String? = nil, challenge: String
    ) {
        self.verifier = verifier
        self.loginHint = loginHint
        self.challenge = challenge
    }
    enum CodingKeys: String, CodingKey {
        case verifier = "verifier"
        case loginHint = "loginHint"
        case challenge = "challenge"
    }
}



package struct CompleteAuthRequest: Codable, Sendable {
    package let identityType: IdentityType
    package let authMode: AuthMode
    package let verifier: String
    package let answer: String
    package let lifetime: UInt32?

    package init(identityType: IdentityType, authMode: AuthMode, verifier: String, answer: String, lifetime: UInt32? = nil
    ) {
        self.identityType = identityType
        self.authMode = authMode
        self.verifier = verifier
        self.answer = answer
        self.lifetime = lifetime
    }
    enum CodingKeys: String, CodingKey {
        case identityType = "identityType"
        case authMode = "authMode"
        case verifier = "verifier"
        case answer = "answer"
        case lifetime = "lifetime"
    }
}



package struct CompleteAuthResponse: Codable, Sendable {
    package let identity: Identity
    package let wallets: [Wallet]
    package let page: Page?
    package let email: String?
    package let credential: CredentialInfo

    package init(identity: Identity, wallets: [Wallet], page: Page? = nil, email: String? = nil, credential: CredentialInfo
    ) {
        self.identity = identity
        self.wallets = wallets
        self.page = page
        self.email = email
        self.credential = credential
    }
    enum CodingKeys: String, CodingKey {
        case identity = "identity"
        case wallets = "wallets"
        case page = "page"
        case email = "email"
        case credential = "credential"
    }
}



package struct CreateWalletRequest: Codable, Sendable {
    package let type: WalletType
    package let reference: String?

    package init(type: WalletType, reference: String? = nil
    ) {
        self.type = type
        self.reference = reference
    }
    enum CodingKeys: String, CodingKey {
        case type = "type"
        case reference = "reference"
    }
}



package struct CreateWalletResponse: Codable, Sendable {
    package let wallet: Wallet

    package init(wallet: Wallet
    ) {
        self.wallet = wallet
    }
    enum CodingKeys: String, CodingKey {
        case wallet = "wallet"
    }
}



package struct UseWalletRequest: Codable, Sendable {
    package let walletId: String

    package init(walletId: String
    ) {
        self.walletId = walletId
    }
    enum CodingKeys: String, CodingKey {
        case walletId = "walletId"
    }
}



package struct UseWalletResponse: Codable, Sendable {
    package let wallet: Wallet

    package init(wallet: Wallet
    ) {
        self.wallet = wallet
    }
    enum CodingKeys: String, CodingKey {
        case wallet = "wallet"
    }
}



package struct SignMessageRequest: Codable, Sendable {
    package let network: String
    package let walletId: String
    package let message: String

    package init(network: String, walletId: String, message: String
    ) {
        self.network = network
        self.walletId = walletId
        self.message = message
    }
    enum CodingKeys: String, CodingKey {
        case network = "network"
        case walletId = "walletId"
        case message = "message"
    }
}



package struct SignMessageResponse: Codable, Sendable {
    package let signature: String

    package init(signature: String
    ) {
        self.signature = signature
    }
    enum CodingKeys: String, CodingKey {
        case signature = "signature"
    }
}



package struct SignTypedDataRequest: Codable, Sendable {
    package let network: String
    package let walletId: String
    package let typedData: WebRPCJSONValue

    package init(network: String, walletId: String, typedData: WebRPCJSONValue
    ) {
        self.network = network
        self.walletId = walletId
        self.typedData = typedData
    }
    enum CodingKeys: String, CodingKey {
        case network = "network"
        case walletId = "walletId"
        case typedData = "typedData"
    }
}



package struct SignTypedDataResponse: Codable, Sendable {
    package let signature: String

    package init(signature: String
    ) {
        self.signature = signature
    }
    enum CodingKeys: String, CodingKey {
        case signature = "signature"
    }
}



package struct AbiArg: Codable, Sendable {
    package let type: String
    package let value: WebRPCJSONValue

    package init(type: String, value: WebRPCJSONValue
    ) {
        self.type = type
        self.value = value
    }
    enum CodingKeys: String, CodingKey {
        case type = "type"
        case value = "value"
    }
}



package struct ListAccessRequest: Codable, Sendable {
    package let walletId: String
    package let page: Page?

    package init(walletId: String, page: Page? = nil
    ) {
        self.walletId = walletId
        self.page = page
    }
    enum CodingKeys: String, CodingKey {
        case walletId = "walletId"
        case page = "page"
    }
}



package struct ListAccessResponse: Codable, Sendable {
    package let credentials: [CredentialInfo]
    package let page: Page?

    package init(credentials: [CredentialInfo], page: Page? = nil
    ) {
        self.credentials = credentials
        self.page = page
    }
    enum CodingKeys: String, CodingKey {
        case credentials = "credentials"
        case page = "page"
    }
}



package struct ListWalletsRequest: Codable, Sendable {
    package let page: Page?

    package init(page: Page? = nil
    ) {
        self.page = page
    }
    enum CodingKeys: String, CodingKey {
        case page = "page"
    }
}



package struct ListWalletsResponse: Codable, Sendable {
    package let wallets: [Wallet]
    package let page: Page?

    package init(wallets: [Wallet], page: Page? = nil
    ) {
        self.wallets = wallets
        self.page = page
    }
    enum CodingKeys: String, CodingKey {
        case wallets = "wallets"
        case page = "page"
    }
}



package struct RevokeAccessRequest: Codable, Sendable {
    package let targetCredentialId: String
    package let walletId: String

    package init(targetCredentialId: String, walletId: String
    ) {
        self.targetCredentialId = targetCredentialId
        self.walletId = walletId
    }
    enum CodingKeys: String, CodingKey {
        case targetCredentialId = "targetCredentialId"
        case walletId = "walletId"
    }
}



package struct RevokeAccessResponse: Codable, Sendable {
    package let ok: Bool

    package init(ok: Bool
    ) {
        self.ok = ok
    }
    enum CodingKeys: String, CodingKey {
        case ok = "ok"
    }
}



package struct PrepareEthereumTransactionRequest: Codable, Sendable {
    package let network: String
    package let walletId: String
    package let to: String
    package let value: String
    package let data: String?
    package let mode: TransactionMode

    package init(network: String, walletId: String, to: String, value: String, data: String? = nil, mode: TransactionMode
    ) {
        self.network = network
        self.walletId = walletId
        self.to = to
        self.value = value
        self.data = data
        self.mode = mode
    }
    enum CodingKeys: String, CodingKey {
        case network = "network"
        case walletId = "walletId"
        case to = "to"
        case value = "value"
        case data = "data"
        case mode = "mode"
    }
}



package struct PrepareEthereumContractCallRequest: Codable, Sendable {
    package let network: String
    package let walletId: String
    package let contract: String
    package let method: String
    package let args: [AbiArg]?
    package let mode: TransactionMode

    package init(network: String, walletId: String, contract: String, method: String, args: [AbiArg]? = nil, mode: TransactionMode
    ) {
        self.network = network
        self.walletId = walletId
        self.contract = contract
        self.method = method
        self.args = args
        self.mode = mode
    }
    enum CodingKeys: String, CodingKey {
        case network = "network"
        case walletId = "walletId"
        case contract = "contract"
        case method = "method"
        case args = "args"
        case mode = "mode"
    }
}



package struct ExecuteRequest: Codable, Sendable {
    package let txnId: String
    package let feeOption: FeeOptionSelection?

    package init(txnId: String, feeOption: FeeOptionSelection? = nil
    ) {
        self.txnId = txnId
        self.feeOption = feeOption
    }
    enum CodingKeys: String, CodingKey {
        case txnId = "txnId"
        case feeOption = "feeOption"
    }
}



package struct TransactionStatusRequest: Codable, Sendable {
    package let txnId: String

    package init(txnId: String
    ) {
        self.txnId = txnId
    }
    enum CodingKeys: String, CodingKey {
        case txnId = "txnId"
    }
}



package struct PrepareResponse: Codable, Sendable {
    package let txnId: String
    package let status: TransactionStatus
    package let feeOptions: [FeeOption]
    package let sponsored: Bool
    package let expiresAt: String

    package init(txnId: String, status: TransactionStatus, feeOptions: [FeeOption], sponsored: Bool, expiresAt: String
    ) {
        self.txnId = txnId
        self.status = status
        self.feeOptions = feeOptions
        self.sponsored = sponsored
        self.expiresAt = expiresAt
    }
    enum CodingKeys: String, CodingKey {
        case txnId = "txnId"
        case status = "status"
        case feeOptions = "feeOptions"
        case sponsored = "sponsored"
        case expiresAt = "expiresAt"
    }
}



package struct ExecuteResponse: Codable, Sendable {
    package let status: TransactionStatus

    package init(status: TransactionStatus
    ) {
        self.status = status
    }
    enum CodingKeys: String, CodingKey {
        case status = "status"
    }
}



package struct TransactionStatusResponse: Codable, Sendable {
    package let status: TransactionStatus
    package let txnHash: String?

    package init(status: TransactionStatus, txnHash: String? = nil
    ) {
        self.status = status
        self.txnHash = txnHash
    }
    enum CodingKeys: String, CodingKey {
        case status = "status"
        case txnHash = "txnHash"
    }
}



package struct CredentialInfo: Codable, Sendable {
    package let credentialId: String
    package let expiresAt: String
    package let isCaller: Bool

    package init(credentialId: String, expiresAt: String, isCaller: Bool
    ) {
        self.credentialId = credentialId
        self.expiresAt = expiresAt
        self.isCaller = isCaller
    }
    enum CodingKeys: String, CodingKey {
        case credentialId = "credentialId"
        case expiresAt = "expiresAt"
        case isCaller = "isCaller"
    }
}



package struct IsValidMessageSignatureRequest: Codable, Sendable {
    package let network: String?
    package let walletAddress: String?
    package let walletId: String?
    package let message: String
    package let signature: String

    package init(network: String? = nil, walletAddress: String? = nil, walletId: String? = nil, message: String, signature: String
    ) {
        self.network = network
        self.walletAddress = walletAddress
        self.walletId = walletId
        self.message = message
        self.signature = signature
    }
    enum CodingKeys: String, CodingKey {
        case network = "network"
        case walletAddress = "walletAddress"
        case walletId = "walletId"
        case message = "message"
        case signature = "signature"
    }
}



package struct IsValidMessageSignatureResponse: Codable, Sendable {
    package let isValid: Bool

    package init(isValid: Bool
    ) {
        self.isValid = isValid
    }
    enum CodingKeys: String, CodingKey {
        case isValid = "isValid"
    }
}



package struct IsValidTypedDataSignatureRequest: Codable, Sendable {
    package let network: String?
    package let walletAddress: String?
    package let walletId: String?
    package let typedData: WebRPCJSONValue
    package let signature: String

    package init(network: String? = nil, walletAddress: String? = nil, walletId: String? = nil, typedData: WebRPCJSONValue, signature: String
    ) {
        self.network = network
        self.walletAddress = walletAddress
        self.walletId = walletId
        self.typedData = typedData
        self.signature = signature
    }
    enum CodingKeys: String, CodingKey {
        case network = "network"
        case walletAddress = "walletAddress"
        case walletId = "walletId"
        case typedData = "typedData"
        case signature = "signature"
    }
}



package struct IsValidTypedDataSignatureResponse: Codable, Sendable {
    package let isValid: Bool

    package init(isValid: Bool
    ) {
        self.isValid = isValid
    }
    enum CodingKeys: String, CodingKey {
        case isValid = "isValid"
    }
}



package struct GetIDTokenRequest: Codable, Sendable {
    package let walletId: String
    package let ttlSeconds: UInt32?
    package let customClaims: [String: WebRPCJSONValue]?

    package init(walletId: String, ttlSeconds: UInt32? = nil, customClaims: [String: WebRPCJSONValue]? = nil
    ) {
        self.walletId = walletId
        self.ttlSeconds = ttlSeconds
        self.customClaims = customClaims
    }
    enum CodingKeys: String, CodingKey {
        case walletId = "walletId"
        case ttlSeconds = "ttlSeconds"
        case customClaims = "customClaims"
    }
}



package struct GetIDTokenResponse: Codable, Sendable {
    package let idToken: String

    package init(idToken: String
    ) {
        self.idToken = idToken
    }
    enum CodingKeys: String, CodingKey {
        case idToken = "idToken"
    }
}



package struct JWK: Codable, Sendable {
    package let alg: String
    package let crv: String
    package let kid: String
    package let kty: String
    package let use: String
    package let x: String
    package let y: String

    package init(alg: String, crv: String, kid: String, kty: String, use: String, x: String, y: String
    ) {
        self.alg = alg
        self.crv = crv
        self.kid = kid
        self.kty = kty
        self.use = use
        self.x = x
        self.y = y
    }
    enum CodingKeys: String, CodingKey {
        case alg = "alg"
        case crv = "crv"
        case kid = "kid"
        case kty = "kty"
        case use = "use"
        case x = "x"
        case y = "y"
    }
}






package enum WaasAPI {
    package static let basePath = "/v1/Waas"

    package enum CommitVerifier {
        package static let path = "/CommitVerifier"
        package static let urlPath = "/v1/Waas/CommitVerifier"
        package static func encodeRequest(
            _ request: CommitVerifierRequest,
            encoder: JSONEncoder = WebRPCJSON.makeEncoder()
        ) throws -> Data {
            try encoder.encode(request)
        }

        package static func decodeResponse(
            _ data: Data,
            decoder: JSONDecoder = WebRPCJSON.makeDecoder()
        ) throws -> CommitVerifierResponse {
            try decoder.decode(CommitVerifierResponse.self, from: data)
        }
    }

    package enum CompleteAuth {
        package static let path = "/CompleteAuth"
        package static let urlPath = "/v1/Waas/CompleteAuth"
        package static func encodeRequest(
            _ request: CompleteAuthRequest,
            encoder: JSONEncoder = WebRPCJSON.makeEncoder()
        ) throws -> Data {
            try encoder.encode(request)
        }

        package static func decodeResponse(
            _ data: Data,
            decoder: JSONDecoder = WebRPCJSON.makeDecoder()
        ) throws -> CompleteAuthResponse {
            try decoder.decode(CompleteAuthResponse.self, from: data)
        }
    }

    package enum CreateWallet {
        package static let path = "/CreateWallet"
        package static let urlPath = "/v1/Waas/CreateWallet"
        package static func encodeRequest(
            _ request: CreateWalletRequest,
            encoder: JSONEncoder = WebRPCJSON.makeEncoder()
        ) throws -> Data {
            try encoder.encode(request)
        }

        package static func decodeResponse(
            _ data: Data,
            decoder: JSONDecoder = WebRPCJSON.makeDecoder()
        ) throws -> CreateWalletResponse {
            try decoder.decode(CreateWalletResponse.self, from: data)
        }
    }

    package enum UseWallet {
        package static let path = "/UseWallet"
        package static let urlPath = "/v1/Waas/UseWallet"
        package static func encodeRequest(
            _ request: UseWalletRequest,
            encoder: JSONEncoder = WebRPCJSON.makeEncoder()
        ) throws -> Data {
            try encoder.encode(request)
        }

        package static func decodeResponse(
            _ data: Data,
            decoder: JSONDecoder = WebRPCJSON.makeDecoder()
        ) throws -> UseWalletResponse {
            try decoder.decode(UseWalletResponse.self, from: data)
        }
    }

    package enum SignMessage {
        package static let path = "/SignMessage"
        package static let urlPath = "/v1/Waas/SignMessage"
        package static func encodeRequest(
            _ request: SignMessageRequest,
            encoder: JSONEncoder = WebRPCJSON.makeEncoder()
        ) throws -> Data {
            try encoder.encode(request)
        }

        package static func decodeResponse(
            _ data: Data,
            decoder: JSONDecoder = WebRPCJSON.makeDecoder()
        ) throws -> SignMessageResponse {
            try decoder.decode(SignMessageResponse.self, from: data)
        }
    }

    package enum SignTypedData {
        package static let path = "/SignTypedData"
        package static let urlPath = "/v1/Waas/SignTypedData"
        package static func encodeRequest(
            _ request: SignTypedDataRequest,
            encoder: JSONEncoder = WebRPCJSON.makeEncoder()
        ) throws -> Data {
            try encoder.encode(request)
        }

        package static func decodeResponse(
            _ data: Data,
            decoder: JSONDecoder = WebRPCJSON.makeDecoder()
        ) throws -> SignTypedDataResponse {
            try decoder.decode(SignTypedDataResponse.self, from: data)
        }
    }

    package enum PrepareEthereumTransaction {
        package static let path = "/PrepareEthereumTransaction"
        package static let urlPath = "/v1/Waas/PrepareEthereumTransaction"
        package static func encodeRequest(
            _ request: PrepareEthereumTransactionRequest,
            encoder: JSONEncoder = WebRPCJSON.makeEncoder()
        ) throws -> Data {
            try encoder.encode(request)
        }

        package static func decodeResponse(
            _ data: Data,
            decoder: JSONDecoder = WebRPCJSON.makeDecoder()
        ) throws -> PrepareResponse {
            try decoder.decode(PrepareResponse.self, from: data)
        }
    }

    package enum PrepareEthereumContractCall {
        package static let path = "/PrepareEthereumContractCall"
        package static let urlPath = "/v1/Waas/PrepareEthereumContractCall"
        package static func encodeRequest(
            _ request: PrepareEthereumContractCallRequest,
            encoder: JSONEncoder = WebRPCJSON.makeEncoder()
        ) throws -> Data {
            try encoder.encode(request)
        }

        package static func decodeResponse(
            _ data: Data,
            decoder: JSONDecoder = WebRPCJSON.makeDecoder()
        ) throws -> PrepareResponse {
            try decoder.decode(PrepareResponse.self, from: data)
        }
    }

    package enum Execute {
        package static let path = "/Execute"
        package static let urlPath = "/v1/Waas/Execute"
        package static func encodeRequest(
            _ request: ExecuteRequest,
            encoder: JSONEncoder = WebRPCJSON.makeEncoder()
        ) throws -> Data {
            try encoder.encode(request)
        }

        package static func decodeResponse(
            _ data: Data,
            decoder: JSONDecoder = WebRPCJSON.makeDecoder()
        ) throws -> ExecuteResponse {
            try decoder.decode(ExecuteResponse.self, from: data)
        }
    }

    package enum TransactionStatusMethod {
        package static let path = "/TransactionStatus"
        package static let urlPath = "/v1/Waas/TransactionStatus"
        package static func encodeRequest(
            _ request: TransactionStatusRequest,
            encoder: JSONEncoder = WebRPCJSON.makeEncoder()
        ) throws -> Data {
            try encoder.encode(request)
        }

        package static func decodeResponse(
            _ data: Data,
            decoder: JSONDecoder = WebRPCJSON.makeDecoder()
        ) throws -> TransactionStatusResponse {
            try decoder.decode(TransactionStatusResponse.self, from: data)
        }
    }

    package enum ListAccess {
        package static let path = "/ListAccess"
        package static let urlPath = "/v1/Waas/ListAccess"
        package static func encodeRequest(
            _ request: ListAccessRequest,
            encoder: JSONEncoder = WebRPCJSON.makeEncoder()
        ) throws -> Data {
            try encoder.encode(request)
        }

        package static func decodeResponse(
            _ data: Data,
            decoder: JSONDecoder = WebRPCJSON.makeDecoder()
        ) throws -> ListAccessResponse {
            try decoder.decode(ListAccessResponse.self, from: data)
        }
    }

    package enum RevokeAccess {
        package static let path = "/RevokeAccess"
        package static let urlPath = "/v1/Waas/RevokeAccess"
        package static func encodeRequest(
            _ request: RevokeAccessRequest,
            encoder: JSONEncoder = WebRPCJSON.makeEncoder()
        ) throws -> Data {
            try encoder.encode(request)
        }

        package static func decodeResponse(
            _ data: Data,
            decoder: JSONDecoder = WebRPCJSON.makeDecoder()
        ) throws -> RevokeAccessResponse {
            try decoder.decode(RevokeAccessResponse.self, from: data)
        }
    }

    package enum ListWallets {
        package static let path = "/ListWallets"
        package static let urlPath = "/v1/Waas/ListWallets"
        package static func encodeRequest(
            _ request: ListWalletsRequest,
            encoder: JSONEncoder = WebRPCJSON.makeEncoder()
        ) throws -> Data {
            try encoder.encode(request)
        }

        package static func decodeResponse(
            _ data: Data,
            decoder: JSONDecoder = WebRPCJSON.makeDecoder()
        ) throws -> ListWalletsResponse {
            try decoder.decode(ListWalletsResponse.self, from: data)
        }
    }

    package enum GetIDToken {
        package static let path = "/GetIDToken"
        package static let urlPath = "/v1/Waas/GetIDToken"
        package static func encodeRequest(
            _ request: GetIDTokenRequest,
            encoder: JSONEncoder = WebRPCJSON.makeEncoder()
        ) throws -> Data {
            try encoder.encode(request)
        }

        package static func decodeResponse(
            _ data: Data,
            decoder: JSONDecoder = WebRPCJSON.makeDecoder()
        ) throws -> GetIDTokenResponse {
            try decoder.decode(GetIDTokenResponse.self, from: data)
        }
    }
}

package struct WaasClient: Sendable {
    package let baseURL: String
    package let transport: any WebRPCTransport
    package let headers: @Sendable () -> [String: String]

    package init(
        baseURL: String,
        transport: any WebRPCTransport = URLSessionWebRPCTransport(),
        headers: @escaping @Sendable () -> [String: String] = { [:] }
    ) {
        self.baseURL = baseURL
        self.transport = transport
        self.headers = headers
    }

    package func commitVerifier(_ request:CommitVerifierRequest) async throws -> CommitVerifierResponse {
        let body = try WaasAPI.CommitVerifier.encodeRequest(request)
        let requestHeaders = makeWebRPCHeaders(
            headers(),
            includeWebRPCHeader: true
        )
        return try await executeWebRPC(
            baseURL: baseURL,
            urlPath: WaasAPI.CommitVerifier.urlPath,
            body: body,
            transport: transport,
            headers: requestHeaders,
            decodeSuccess: WaasAPI.CommitVerifier.decodeResponse,
        )
    }

    package func completeAuth(_ request:CompleteAuthRequest) async throws -> CompleteAuthResponse {
        let body = try WaasAPI.CompleteAuth.encodeRequest(request)
        let requestHeaders = makeWebRPCHeaders(
            headers(),
            includeWebRPCHeader: true
        )
        return try await executeWebRPC(
            baseURL: baseURL,
            urlPath: WaasAPI.CompleteAuth.urlPath,
            body: body,
            transport: transport,
            headers: requestHeaders,
            decodeSuccess: WaasAPI.CompleteAuth.decodeResponse,
        )
    }

    package func createWallet(_ request:CreateWalletRequest) async throws -> CreateWalletResponse {
        let body = try WaasAPI.CreateWallet.encodeRequest(request)
        let requestHeaders = makeWebRPCHeaders(
            headers(),
            includeWebRPCHeader: true
        )
        return try await executeWebRPC(
            baseURL: baseURL,
            urlPath: WaasAPI.CreateWallet.urlPath,
            body: body,
            transport: transport,
            headers: requestHeaders,
            decodeSuccess: WaasAPI.CreateWallet.decodeResponse,
        )
    }

    package func useWallet(_ request:UseWalletRequest) async throws -> UseWalletResponse {
        let body = try WaasAPI.UseWallet.encodeRequest(request)
        let requestHeaders = makeWebRPCHeaders(
            headers(),
            includeWebRPCHeader: true
        )
        return try await executeWebRPC(
            baseURL: baseURL,
            urlPath: WaasAPI.UseWallet.urlPath,
            body: body,
            transport: transport,
            headers: requestHeaders,
            decodeSuccess: WaasAPI.UseWallet.decodeResponse,
        )
    }

    package func signMessage(_ request:SignMessageRequest) async throws -> SignMessageResponse {
        let body = try WaasAPI.SignMessage.encodeRequest(request)
        let requestHeaders = makeWebRPCHeaders(
            headers(),
            includeWebRPCHeader: true
        )
        return try await executeWebRPC(
            baseURL: baseURL,
            urlPath: WaasAPI.SignMessage.urlPath,
            body: body,
            transport: transport,
            headers: requestHeaders,
            decodeSuccess: WaasAPI.SignMessage.decodeResponse,
        )
    }

    package func signTypedData(_ request:SignTypedDataRequest) async throws -> SignTypedDataResponse {
        let body = try WaasAPI.SignTypedData.encodeRequest(request)
        let requestHeaders = makeWebRPCHeaders(
            headers(),
            includeWebRPCHeader: true
        )
        return try await executeWebRPC(
            baseURL: baseURL,
            urlPath: WaasAPI.SignTypedData.urlPath,
            body: body,
            transport: transport,
            headers: requestHeaders,
            decodeSuccess: WaasAPI.SignTypedData.decodeResponse,
        )
    }

    package func prepareEthereumTransaction(_ request:PrepareEthereumTransactionRequest) async throws -> PrepareResponse {
        let body = try WaasAPI.PrepareEthereumTransaction.encodeRequest(request)
        let requestHeaders = makeWebRPCHeaders(
            headers(),
            includeWebRPCHeader: true
        )
        return try await executeWebRPC(
            baseURL: baseURL,
            urlPath: WaasAPI.PrepareEthereumTransaction.urlPath,
            body: body,
            transport: transport,
            headers: requestHeaders,
            decodeSuccess: WaasAPI.PrepareEthereumTransaction.decodeResponse,
        )
    }

    package func prepareEthereumContractCall(_ request:PrepareEthereumContractCallRequest) async throws -> PrepareResponse {
        let body = try WaasAPI.PrepareEthereumContractCall.encodeRequest(request)
        let requestHeaders = makeWebRPCHeaders(
            headers(),
            includeWebRPCHeader: true
        )
        return try await executeWebRPC(
            baseURL: baseURL,
            urlPath: WaasAPI.PrepareEthereumContractCall.urlPath,
            body: body,
            transport: transport,
            headers: requestHeaders,
            decodeSuccess: WaasAPI.PrepareEthereumContractCall.decodeResponse,
        )
    }

    package func execute(_ request:ExecuteRequest) async throws -> ExecuteResponse {
        let body = try WaasAPI.Execute.encodeRequest(request)
        let requestHeaders = makeWebRPCHeaders(
            headers(),
            includeWebRPCHeader: true
        )
        return try await executeWebRPC(
            baseURL: baseURL,
            urlPath: WaasAPI.Execute.urlPath,
            body: body,
            transport: transport,
            headers: requestHeaders,
            decodeSuccess: WaasAPI.Execute.decodeResponse,
        )
    }

    package func transactionStatus(_ request:TransactionStatusRequest) async throws -> TransactionStatusResponse {
        let body = try WaasAPI.TransactionStatusMethod.encodeRequest(request)
        let requestHeaders = makeWebRPCHeaders(
            headers(),
            includeWebRPCHeader: true
        )
        return try await executeWebRPC(
            baseURL: baseURL,
            urlPath: WaasAPI.TransactionStatusMethod.urlPath,
            body: body,
            transport: transport,
            headers: requestHeaders,
            decodeSuccess: WaasAPI.TransactionStatusMethod.decodeResponse,
        )
    }

    package func listAccess(_ request:ListAccessRequest) async throws -> ListAccessResponse {
        let body = try WaasAPI.ListAccess.encodeRequest(request)
        let requestHeaders = makeWebRPCHeaders(
            headers(),
            includeWebRPCHeader: true
        )
        return try await executeWebRPC(
            baseURL: baseURL,
            urlPath: WaasAPI.ListAccess.urlPath,
            body: body,
            transport: transport,
            headers: requestHeaders,
            decodeSuccess: WaasAPI.ListAccess.decodeResponse,
        )
    }

    package func revokeAccess(_ request:RevokeAccessRequest) async throws -> RevokeAccessResponse {
        let body = try WaasAPI.RevokeAccess.encodeRequest(request)
        let requestHeaders = makeWebRPCHeaders(
            headers(),
            includeWebRPCHeader: true
        )
        return try await executeWebRPC(
            baseURL: baseURL,
            urlPath: WaasAPI.RevokeAccess.urlPath,
            body: body,
            transport: transport,
            headers: requestHeaders,
            decodeSuccess: WaasAPI.RevokeAccess.decodeResponse,
        )
    }

    package func listWallets(_ request:ListWalletsRequest) async throws -> ListWalletsResponse {
        let body = try WaasAPI.ListWallets.encodeRequest(request)
        let requestHeaders = makeWebRPCHeaders(
            headers(),
            includeWebRPCHeader: true
        )
        return try await executeWebRPC(
            baseURL: baseURL,
            urlPath: WaasAPI.ListWallets.urlPath,
            body: body,
            transport: transport,
            headers: requestHeaders,
            decodeSuccess: WaasAPI.ListWallets.decodeResponse,
        )
    }

    package func getIdToken(_ request:GetIDTokenRequest) async throws -> GetIDTokenResponse {
        let body = try WaasAPI.GetIDToken.encodeRequest(request)
        let requestHeaders = makeWebRPCHeaders(
            headers(),
            includeWebRPCHeader: true
        )
        return try await executeWebRPC(
            baseURL: baseURL,
            urlPath: WaasAPI.GetIDToken.urlPath,
            body: body,
            transport: transport,
            headers: requestHeaders,
            decodeSuccess: WaasAPI.GetIDToken.decodeResponse,
        )
    }
}


package enum WaasPublicAPI {
    package static let basePath = "/v1/WaasPublic"

    package enum Status {
        package static let path = "/Status"
        package static let urlPath = "/v1/WaasPublic/Status"

        package struct Response: Codable, Sendable {
            package let ver: String
            package let env: String
            package let pcr0: String

            package init(ver: String, env: String, pcr0: String
            ) {
                self.ver = ver
                self.env = env
                self.pcr0 = pcr0
            }
            enum CodingKeys: String, CodingKey {
                case ver = "ver"
                case env = "env"
                case pcr0 = "pcr0"
            }
        }
        package static func encodeRequest(encoder _: JSONEncoder = WebRPCJSON.makeEncoder()) throws -> Data {
            Data("{}".utf8)
        }

        package static func decodeResponse(
            _ data: Data,
            decoder: JSONDecoder = WebRPCJSON.makeDecoder()
        ) throws -> WaasPublicAPI.Status.Response {
            try decoder.decode(WaasPublicAPI.Status.Response.self, from: data)
        }
    }

    package enum GetJWKS {
        package static let path = "/GetJWKS"
        package static let urlPath = "/v1/WaasPublic/GetJWKS"

        package struct Response: Codable, Sendable {
            package let keys: [JWK]

            package init(keys: [JWK]
            ) {
                self.keys = keys
            }
            enum CodingKeys: String, CodingKey {
                case keys = "keys"
            }
        }
        package static func encodeRequest(encoder _: JSONEncoder = WebRPCJSON.makeEncoder()) throws -> Data {
            Data("{}".utf8)
        }

        package static func decodeResponse(
            _ data: Data,
            decoder: JSONDecoder = WebRPCJSON.makeDecoder()
        ) throws -> WaasPublicAPI.GetJWKS.Response {
            try decoder.decode(WaasPublicAPI.GetJWKS.Response.self, from: data)
        }
    }

    package enum IsValidMessageSignature {
        package static let path = "/IsValidMessageSignature"
        package static let urlPath = "/v1/WaasPublic/IsValidMessageSignature"
        package static func encodeRequest(
            _ request: IsValidMessageSignatureRequest,
            encoder: JSONEncoder = WebRPCJSON.makeEncoder()
        ) throws -> Data {
            try encoder.encode(request)
        }

        package static func decodeResponse(
            _ data: Data,
            decoder: JSONDecoder = WebRPCJSON.makeDecoder()
        ) throws -> IsValidMessageSignatureResponse {
            try decoder.decode(IsValidMessageSignatureResponse.self, from: data)
        }
    }

    package enum IsValidTypedDataSignature {
        package static let path = "/IsValidTypedDataSignature"
        package static let urlPath = "/v1/WaasPublic/IsValidTypedDataSignature"
        package static func encodeRequest(
            _ request: IsValidTypedDataSignatureRequest,
            encoder: JSONEncoder = WebRPCJSON.makeEncoder()
        ) throws -> Data {
            try encoder.encode(request)
        }

        package static func decodeResponse(
            _ data: Data,
            decoder: JSONDecoder = WebRPCJSON.makeDecoder()
        ) throws -> IsValidTypedDataSignatureResponse {
            try decoder.decode(IsValidTypedDataSignatureResponse.self, from: data)
        }
    }
}

package struct WaasPublicClient: Sendable {
    package let baseURL: String
    package let transport: any WebRPCTransport
    package let headers: @Sendable () -> [String: String]

    package init(
        baseURL: String,
        transport: any WebRPCTransport = URLSessionWebRPCTransport(),
        headers: @escaping @Sendable () -> [String: String] = { [:] }
    ) {
        self.baseURL = baseURL
        self.transport = transport
        self.headers = headers
    }

    package func status() async throws -> WaasPublicAPI.Status.Response {
        let body = try WaasPublicAPI.Status.encodeRequest()
        let requestHeaders = makeWebRPCHeaders(
            headers(),
            includeWebRPCHeader: true
        )
        return try await executeWebRPC(
            baseURL: baseURL,
            urlPath: WaasPublicAPI.Status.urlPath,
            body: body,
            transport: transport,
            headers: requestHeaders,
            decodeSuccess: WaasPublicAPI.Status.decodeResponse,
        )
    }

    package func getJwks() async throws -> WaasPublicAPI.GetJWKS.Response {
        let body = try WaasPublicAPI.GetJWKS.encodeRequest()
        let requestHeaders = makeWebRPCHeaders(
            headers(),
            includeWebRPCHeader: true
        )
        return try await executeWebRPC(
            baseURL: baseURL,
            urlPath: WaasPublicAPI.GetJWKS.urlPath,
            body: body,
            transport: transport,
            headers: requestHeaders,
            decodeSuccess: WaasPublicAPI.GetJWKS.decodeResponse,
        )
    }

    package func isValidMessageSignature(_ request:IsValidMessageSignatureRequest) async throws -> IsValidMessageSignatureResponse {
        let body = try WaasPublicAPI.IsValidMessageSignature.encodeRequest(request)
        let requestHeaders = makeWebRPCHeaders(
            headers(),
            includeWebRPCHeader: true
        )
        return try await executeWebRPC(
            baseURL: baseURL,
            urlPath: WaasPublicAPI.IsValidMessageSignature.urlPath,
            body: body,
            transport: transport,
            headers: requestHeaders,
            decodeSuccess: WaasPublicAPI.IsValidMessageSignature.decodeResponse,
        )
    }

    package func isValidTypedDataSignature(_ request:IsValidTypedDataSignatureRequest) async throws -> IsValidTypedDataSignatureResponse {
        let body = try WaasPublicAPI.IsValidTypedDataSignature.encodeRequest(request)
        let requestHeaders = makeWebRPCHeaders(
            headers(),
            includeWebRPCHeader: true
        )
        return try await executeWebRPC(
            baseURL: baseURL,
            urlPath: WaasPublicAPI.IsValidTypedDataSignature.urlPath,
            body: body,
            transport: transport,
            headers: requestHeaders,
            decodeSuccess: WaasPublicAPI.IsValidTypedDataSignature.decodeResponse,
        )
    }
}


