// Generated by oms-sdk-design-system. Do not edit manually.
// swiftlint:disable all

import SwiftUI

public enum OMSButtonVariant: Sendable {
    case primary
    case secondary
    case dangerPrimary
    case dangerSecondary
}

public enum OMSButtonSize: Sendable {
    case small
    case medium
    case large
}

public enum OMSLabelVariant: Sendable {
    case title
    case body
    case caption
    case subtle
    case error
}

public enum OMSFieldState: Sendable {
    case normal
    case error(String)
    case disabled
}

public enum OMSBadgeVariant: Sendable {
    case info
    case neutral
    case success
    case warning
    case danger
}

public enum OMSAlertVariant: Sendable {
    case info
    case success
    case warning
    case danger
}

public enum OMSTokens {
    public enum Color {
        public static let slate50 = SwiftUI.Color(red: 0.96, green: 0.96, blue: 0.99)
        public static let slate100 = SwiftUI.Color(red: 0.93, green: 0.94, blue: 0.98)
        public static let slate200 = SwiftUI.Color(red: 0.87, green: 0.89, blue: 0.94)
        public static let slate300 = SwiftUI.Color(red: 0.78, green: 0.81, blue: 0.88)
        public static let slate400 = SwiftUI.Color(red: 0.57, green: 0.62, blue: 0.73)
        public static let slate500 = SwiftUI.Color(red: 0.39, green: 0.44, blue: 0.56)
        public static let slate800 = SwiftUI.Color(red: 0.13, green: 0.15, blue: 0.27)
        public static let slate900 = SwiftUI.Color(red: 0.08, green: 0.09, blue: 0.21)
        public static let slate950 = SwiftUI.Color(red: 0.04, green: 0.02, blue: 0.14)
        public static let purple50 = SwiftUI.Color(red: 0.96, green: 0.95, blue: 0.98)
        public static let purple100 = SwiftUI.Color(red: 0.92, green: 0.89, blue: 0.96)
        public static let purple200 = SwiftUI.Color(red: 0.84, green: 0.77, blue: 0.95)
        public static let purple300 = SwiftUI.Color(red: 0.72, green: 0.56, blue: 0.94)
        public static let purple500 = SwiftUI.Color(red: 0.40, green: 0.05, blue: 0.90)
        public static let purple700 = SwiftUI.Color(red: 0.25, green: 0.04, blue: 0.56)
        public static let red50 = SwiftUI.Color(red: 1.00, green: 0.95, blue: 0.95)
        public static let red100 = SwiftUI.Color(red: 1.00, green: 0.89, blue: 0.89)
        public static let red200 = SwiftUI.Color(red: 1.00, green: 0.79, blue: 0.79)
        public static let red400 = SwiftUI.Color(red: 0.97, green: 0.44, blue: 0.44)
        public static let red500 = SwiftUI.Color(red: 0.94, green: 0.27, blue: 0.27)
        public static let red600 = SwiftUI.Color(red: 0.86, green: 0.15, blue: 0.15)
        public static let red700 = SwiftUI.Color(red: 0.73, green: 0.11, blue: 0.11)
        public static let red800 = SwiftUI.Color(red: 0.60, green: 0.11, blue: 0.11)
        public static let emerald50 = SwiftUI.Color(red: 0.93, green: 0.99, blue: 0.96)
        public static let emerald200 = SwiftUI.Color(red: 0.65, green: 0.95, blue: 0.82)
        public static let emerald700 = SwiftUI.Color(red: 0.02, green: 0.47, blue: 0.34)
        public static let orange50 = SwiftUI.Color(red: 1.00, green: 0.97, blue: 0.93)
        public static let orange200 = SwiftUI.Color(red: 1.00, green: 0.84, blue: 0.67)
        public static let amber700 = SwiftUI.Color(red: 0.71, green: 0.33, blue: 0.04)
        public static let surface = SwiftUI.Color.white
        public static let page = slate50
        public static let ink = slate900
        public static let mutedInk = slate500
        public static let border = slate300
        public static let brand = purple500
        public static let success = emerald700
        public static let warning = amber700
        public static let danger = red700
    }

    public enum Radius {
        public static let button: CGFloat = 8
        public static let buttonLarge: CGFloat = 12
        public static let input: CGFloat = 12
        public static let badge: CGFloat = 16
        public static let card: CGFloat = 24
    }

    public enum Spacing {
        public static let xsmall: CGFloat = 4
        public static let small: CGFloat = 8
        public static let medium: CGFloat = 12
        public static let large: CGFloat = 16
        public static let xlarge: CGFloat = 24
    }
}

public struct OMSButtonStyle: ButtonStyle {
    private let variant: OMSButtonVariant
    private let size: OMSButtonSize
    private let fillsWidth: Bool

    public init(
        variant: OMSButtonVariant = .primary,
        size: OMSButtonSize = .medium,
        fillsWidth: Bool = false
    ) {
        self.variant = variant
        self.size = size
        self.fillsWidth = fillsWidth
    }

    public func makeBody(configuration: Configuration) -> some View {
        configuration.label
            .font(font)
            .lineLimit(1)
            .minimumScaleFactor(0.9)
            .padding(.horizontal, horizontalPadding)
            .frame(minHeight: height)
            .frame(maxWidth: fillsWidth ? .infinity : nil)
            .background(backgroundColor(isPressed: configuration.isPressed))
            .foregroundStyle(foregroundColor)
            .overlay(
                RoundedRectangle(cornerRadius: cornerRadius)
                    .stroke(borderColor, lineWidth: borderColor == .clear ? 0 : 1)
            )
            .clipShape(RoundedRectangle(cornerRadius: cornerRadius))
            .contentShape(RoundedRectangle(cornerRadius: cornerRadius))
    }

    private var font: Font {
        switch size {
        case .small:
            return .custom("Fustat", size: 12).weight(.bold)
        case .medium:
            return .custom("Fustat", size: 14).weight(.bold)
        case .large:
            return .custom("Fustat", size: 16).weight(.bold)
        }
    }

    private var height: CGFloat {
        switch size {
        case .small:
            return 30
        case .medium:
            return 32
        case .large:
            return 40
        }
    }

    private var horizontalPadding: CGFloat {
        switch size {
        case .small:
            return 8
        case .medium:
            return 12
        case .large:
            return 12
        }
    }

    private var cornerRadius: CGFloat {
        switch size {
        case .large:
            return OMSTokens.Radius.buttonLarge
        case .medium, .small:
            return OMSTokens.Radius.button
        }
    }

    private func backgroundColor(isPressed: Bool) -> SwiftUI.Color {
        switch variant {
        case .primary:
            return isPressed ? OMSTokens.Color.purple700 : OMSTokens.Color.slate950
        case .secondary:
            return isPressed ? OMSTokens.Color.purple100 : OMSTokens.Color.surface
        case .dangerPrimary:
            return isPressed ? OMSTokens.Color.red800 : OMSTokens.Color.red600
        case .dangerSecondary:
            return isPressed ? OMSTokens.Color.red100 : OMSTokens.Color.surface
        }
    }

    private var foregroundColor: SwiftUI.Color {
        switch variant {
        case .primary, .dangerPrimary:
            return .white
        case .secondary, .dangerSecondary:
            return OMSTokens.Color.slate950
        }
    }

    private var borderColor: SwiftUI.Color {
        switch variant {
        case .primary, .dangerPrimary:
            return .clear
        case .secondary:
            return OMSTokens.Color.slate500
        case .dangerSecondary:
            return OMSTokens.Color.red600
        }
    }
}

public struct OMSButton: View {
    private let variant: OMSButtonVariant
    private let size: OMSButtonSize
    private let fillsWidth: Bool
    private let text: String
    private let action: () -> Void

    public init(
        _ text: String,
        variant: OMSButtonVariant = .primary,
        size: OMSButtonSize = .medium,
        fillsWidth: Bool = false,
        action: @escaping () -> Void
    ) {
        self.text = text
        self.variant = variant
        self.size = size
        self.fillsWidth = fillsWidth
        self.action = action
    }

    public var body: some View {
        Button(text, action: action)
            .buttonStyle(OMSButtonStyle(variant: variant, size: size, fillsWidth: fillsWidth))
    }
}

public struct OMSIconButton: View {
    private let systemImage: String
    private let accessibilityLabel: String
    private let size: CGFloat
    private let action: () -> Void

    public init(
        systemImage: String,
        accessibilityLabel: String,
        size: CGFloat = 40,
        action: @escaping () -> Void
    ) {
        self.systemImage = systemImage
        self.accessibilityLabel = accessibilityLabel
        self.size = size
        self.action = action
    }

    public var body: some View {
        Button(action: action) {
            Image(systemName: systemImage)
                .font(.system(size: size * 0.38, weight: .semibold))
                .frame(width: size, height: size)
                .background(OMSTokens.Color.surface)
                .foregroundStyle(OMSTokens.Color.slate950)
                .overlay(RoundedRectangle(cornerRadius: OMSTokens.Radius.buttonLarge).stroke(OMSTokens.Color.slate300, lineWidth: 1))
                .clipShape(RoundedRectangle(cornerRadius: OMSTokens.Radius.buttonLarge))
        }
        .buttonStyle(.plain)
        .accessibilityLabel(accessibilityLabel)
    }
}

public struct OMSIconLabelButton: View {
    private let systemImage: String
    private let text: String
    private let action: () -> Void

    public init(systemImage: String, text: String, action: @escaping () -> Void) {
        self.systemImage = systemImage
        self.text = text
        self.action = action
    }

    public var body: some View {
        VStack(spacing: OMSTokens.Spacing.small) {
            OMSIconButton(systemImage: systemImage, accessibilityLabel: text, size: 40, action: action)
            Text(text)
                .font(.custom("Fustat", size: 12).weight(.medium))
                .foregroundStyle(OMSTokens.Color.slate900)
                .multilineTextAlignment(.center)
        }
    }
}

public struct OMSLabel: View {
    private let text: String
    private let variant: OMSLabelVariant

    public init(_ text: String, variant: OMSLabelVariant = .body) {
        self.text = text
        self.variant = variant
    }

    public var body: some View {
        Text(text)
            .font(font)
            .foregroundStyle(color)
            .fixedSize(horizontal: false, vertical: true)
    }

    private var font: Font {
        switch variant {
        case .title:
            return .custom("Fustat", size: 24).weight(.bold)
        case .body:
            return .custom("Fustat", size: 16).weight(.medium)
        case .caption:
            return .custom("Fustat", size: 14).weight(.medium)
        case .subtle:
            return .custom("Fustat", size: 12).weight(.medium)
        case .error:
            return .custom("Fustat", size: 14).weight(.medium)
        }
    }

    private var color: SwiftUI.Color {
        switch variant {
        case .title:
            return OMSTokens.Color.slate950
        case .body:
            return OMSTokens.Color.slate900
        case .caption, .subtle:
            return OMSTokens.Color.slate500
        case .error:
            return OMSTokens.Color.red700
        }
    }
}

public struct OMSInputField: View {
    private let title: String
    private let placeholder: String
    private let helperText: String?
    private let state: OMSFieldState
    @Binding private var text: String

    public init(
        _ title: String,
        text: Binding<String>,
        placeholder: String = "",
        helperText: String? = nil,
        state: OMSFieldState = .normal
    ) {
        self.title = title
        self._text = text
        self.placeholder = placeholder
        self.helperText = helperText
        self.state = state
    }

    public var body: some View {
        VStack(alignment: .leading, spacing: OMSTokens.Spacing.xsmall) {
            OMSLabel(title, variant: .caption)
            TextField(placeholder, text: $text)
                .disabled(isDisabled)
                .padding(.horizontal, OMSTokens.Spacing.medium)
                .font(.custom("Fustat", size: 14).weight(.medium))
                .frame(minHeight: 40)
                .background(OMSTokens.Color.surface)
                .foregroundStyle(OMSTokens.Color.slate900)
                .overlay(
                    RoundedRectangle(cornerRadius: OMSTokens.Radius.input)
                        .stroke(borderColor, lineWidth: 1)
                )
                .clipShape(RoundedRectangle(cornerRadius: OMSTokens.Radius.input))
                .opacity(isDisabled ? 0.5 : 1)

            if let message = messageText {
                OMSLabel(message, variant: messageIsError ? .error : .caption)
            }
        }
    }

    private var isDisabled: Bool {
        if case .disabled = state { return true }
        return false
    }

    private var messageText: String? {
        if case .error(let message) = state { return message }
        return helperText
    }

    private var messageIsError: Bool {
        if case .error = state { return true }
        return false
    }

    private var borderColor: SwiftUI.Color {
        switch state {
        case .normal:
            return OMSTokens.Color.slate300
        case .error:
            return OMSTokens.Color.slate300
        case .disabled:
            return OMSTokens.Color.slate300
        }
    }
}

public struct OMSDropdown<Option: Hashable & CustomStringConvertible>: View {
    private let title: String
    private let options: [Option]
    @Binding private var selection: Option

    public init(_ title: String, selection: Binding<Option>, options: [Option]) {
        self.title = title
        self._selection = selection
        self.options = options
    }

    public var body: some View {
        VStack(alignment: .leading, spacing: OMSTokens.Spacing.xsmall) {
            OMSLabel(title, variant: .caption)
            Picker(title, selection: $selection) {
                ForEach(options, id: \.self) { option in
                    Text(option.description).tag(option)
                }
            }
            .pickerStyle(.menu)
            .frame(maxWidth: .infinity, alignment: .leading)
            .padding(.horizontal, OMSTokens.Spacing.medium)
            .font(.custom("Fustat", size: 14).weight(.medium))
            .frame(minHeight: 40)
            .background(OMSTokens.Color.surface)
            .overlay(
                RoundedRectangle(cornerRadius: OMSTokens.Radius.input)
                    .stroke(OMSTokens.Color.slate300, lineWidth: 1)
            )
            .clipShape(RoundedRectangle(cornerRadius: OMSTokens.Radius.input))
        }
    }
}

public struct OMSToggle: View {
    private let title: String
    @Binding private var isOn: Bool

    public init(_ title: String, isOn: Binding<Bool>) {
        self.title = title
        self._isOn = isOn
    }

    public var body: some View {
        Toggle(title, isOn: $isOn)
            .font(.custom("Fustat", size: 14).weight(.medium))
            .foregroundStyle(OMSTokens.Color.slate900)
            .tint(OMSTokens.Color.purple500)
    }
}

public struct OMSBadge: View {
    private let text: String
    private let variant: OMSBadgeVariant

    public init(_ text: String, variant: OMSBadgeVariant = .neutral) {
        self.text = text
        self.variant = variant
    }

    public var body: some View {
        Text(text)
            .font(.custom("Fustat", size: 14).weight(.medium))
            .foregroundStyle(foregroundColor)
            .padding(.horizontal, OMSTokens.Spacing.small)
            .padding(.vertical, OMSTokens.Spacing.xsmall)
            .background(backgroundColor)
            .overlay(RoundedRectangle(cornerRadius: OMSTokens.Radius.badge).stroke(borderColor, lineWidth: 0.5))
            .clipShape(RoundedRectangle(cornerRadius: OMSTokens.Radius.badge))
    }

    private var backgroundColor: SwiftUI.Color {
        switch variant {
        case .info:
            return OMSTokens.Color.purple50
        case .neutral:
            return OMSTokens.Color.slate50
        case .success:
            return OMSTokens.Color.emerald50
        case .warning:
            return OMSTokens.Color.orange50
        case .danger:
            return OMSTokens.Color.red50
        }
    }

    private var foregroundColor: SwiftUI.Color {
        switch variant {
        case .info:
            return OMSTokens.Color.purple700
        case .neutral:
            return OMSTokens.Color.slate900
        case .success:
            return OMSTokens.Color.emerald700
        case .warning:
            return OMSTokens.Color.amber700
        case .danger:
            return OMSTokens.Color.red700
        }
    }

    private var borderColor: SwiftUI.Color {
        switch variant {
        case .info:
            return OMSTokens.Color.purple200
        case .neutral:
            return OMSTokens.Color.slate300
        case .success:
            return OMSTokens.Color.emerald200
        case .warning:
            return OMSTokens.Color.orange200
        case .danger:
            return OMSTokens.Color.red200
        }
    }
}

public struct OMSAlert: View {
    private let title: String
    private let message: String
    private let variant: OMSAlertVariant

    public init(_ title: String, message: String, variant: OMSAlertVariant = .info) {
        self.title = title
        self.message = message
        self.variant = variant
    }

    public var body: some View {
        HStack(alignment: .top, spacing: OMSTokens.Spacing.medium) {
            Image(systemName: iconName)
                .font(.system(size: 16, weight: .medium))
                .foregroundStyle(accentColor)
            VStack(alignment: .leading, spacing: OMSTokens.Spacing.small) {
                Text(title)
                    .font(.custom("Fustat", size: 14).weight(.bold))
                    .foregroundStyle(OMSTokens.Color.slate950)
                Text(message)
                    .font(.custom("Fustat", size: 13).weight(.medium))
                    .foregroundStyle(accentColor)
            }
        }
        .padding(OMSTokens.Spacing.large)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(backgroundColor)
        .overlay(RoundedRectangle(cornerRadius: OMSTokens.Radius.card).stroke(borderColor, lineWidth: 1))
        .clipShape(RoundedRectangle(cornerRadius: OMSTokens.Radius.card))
    }

    private var iconName: String {
        switch variant {
        case .info:
            return "info.circle"
        case .success:
            return "checkmark.circle"
        case .warning:
            return "exclamationmark.triangle"
        case .danger:
            return "xmark.octagon"
        }
    }

    private var backgroundColor: SwiftUI.Color {
        switch variant {
        case .info:
            return OMSTokens.Color.purple50
        case .success:
            return OMSTokens.Color.emerald50
        case .warning:
            return OMSTokens.Color.orange50
        case .danger:
            return OMSTokens.Color.red50
        }
    }

    private var borderColor: SwiftUI.Color {
        switch variant {
        case .info:
            return OMSTokens.Color.purple200
        case .success:
            return OMSTokens.Color.emerald200
        case .warning:
            return OMSTokens.Color.orange200
        case .danger:
            return OMSTokens.Color.red200
        }
    }

    private var accentColor: SwiftUI.Color {
        switch variant {
        case .info:
            return OMSTokens.Color.purple700
        case .success:
            return OMSTokens.Color.emerald700
        case .warning:
            return OMSTokens.Color.amber700
        case .danger:
            return OMSTokens.Color.red700
        }
    }
}

public struct OMSCard<Content: View>: View {
    private let content: () -> Content

    public init(@ViewBuilder content: @escaping () -> Content) {
        self.content = content
    }

    public var body: some View {
        VStack(alignment: .leading, spacing: OMSTokens.Spacing.medium, content: content)
            .padding(OMSTokens.Spacing.large)
            .frame(maxWidth: .infinity, alignment: .leading)
            .background(OMSTokens.Color.surface)
            .overlay(
                RoundedRectangle(cornerRadius: OMSTokens.Radius.card)
                    .stroke(OMSTokens.Color.slate200, lineWidth: 1)
            )
            .clipShape(RoundedRectangle(cornerRadius: OMSTokens.Radius.card))
    }
}
