#!/usr/bin/env python3

import importlib.util
import sys
import unittest
from pathlib import Path


sys.dont_write_bytecode = True
SCRIPT_PATH = Path(__file__).with_name("generate-api.py")
FIXTURE_PATH = Path(__file__).parent / "fixtures" / "api-generator" / "PublicAPI.swift"
SPEC = importlib.util.spec_from_file_location("generate_api", SCRIPT_PATH)
assert SPEC is not None and SPEC.loader is not None
generate_api = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = generate_api
SPEC.loader.exec_module(generate_api)


def fixture_position(name, occurrence=1):
    remaining = occurrence
    for line_number, line in enumerate(FIXTURE_PATH.read_text(encoding="utf-8").splitlines()):
        search_start = 0
        while True:
            character = line.find(name, search_start)
            if character == -1:
                break
            remaining -= 1
            if remaining == 0:
                return line_number, len(line[:character].encode("utf-8"))
            search_start = character + len(name)
    raise AssertionError(f"Fixture occurrence is missing: {name} #{occurrence}")


def symbol(
    identifier,
    path,
    declaration,
    kind,
    source_name,
    parent=None,
    summary=None,
    occurrence=1,
):
    line, character = fixture_position(source_name, occurrence)
    value = {
        "accessLevel": "public",
        "identifier": {"precise": identifier},
        "kind": {"identifier": kind},
        "pathComponents": path.split("."),
        "declarationFragments": [{"spelling": part} for part in declaration],
        "location": {
            "uri": FIXTURE_PATH.resolve().as_uri(),
            "position": {"line": line, "character": character},
        },
    }
    if summary is not None:
        value["docComment"] = {
            "module": "OMSWallet",
            "lines": [{"text": text} for text in summary.split("\n")]
        }
    relationship = (
        {"kind": "memberOf", "source": identifier, "target": parent}
        if parent is not None
        else None
    )
    return value, relationship


def graph(values, relationships=None):
    return {
        "module": {"name": "OMSWallet"},
        "symbols": [value for value, _ in values],
        "relationships": [
            relationship for _, relationship in values if relationship is not None
        ]
        + (relationships or []),
    }


def config(first_group_entries, second_group_entries=None):
    return [
        {"label": "OMSWallet", "symbols": first_group_entries},
        {
            "label": "Authentication and sessions",
            "symbols": second_group_entries or [],
        },
        {"label": "Transactions and signing", "symbols": []},
        {"label": "Indexer", "symbols": []},
        {"label": "Networks, types, and errors", "symbols": []},
    ]


class GenerateAPITests(unittest.TestCase):
    def setUp(self):
        values = [
            symbol("root", "Wallet", ["struct ", "Wallet"], "swift.struct", "Wallet"),
            symbol(
                "first-overload",
                "Wallet.sign(_:)",
                ["func sign(_ value: ", "String", ")"],
                "swift.method",
                "sign",
                parent="root",
                summary="Signs a value.\n\n- Parameter value: The value.",
            ),
            symbol(
                "second-overload",
                "Wallet.sign(_:)",
                ["func sign(_ value: ", "Data", ")"],
                "swift.method",
                "sign",
                parent="root",
                occurrence=2,
            ),
        ]
        self.symbols = generate_api.public_symbols(
            graph(
                values,
                [
                    {
                        "kind": "conformsTo",
                        "source": "root",
                        "target": "sendable",
                        "targetFallback": "Swift.Sendable",
                    },
                    {
                        "kind": "conformsTo",
                        "source": "root",
                        "target": "sendable-metatype",
                        "targetFallback": "Swift.SendableMetatype",
                    },
                ],
            )
        )

    def test_compound_type_renders_exact_fragments_and_source_summaries(self):
        groups = generate_api.ordered_symbols(
            self.symbols, config([{"path": "Wallet"}])
        )

        output = generate_api.render(groups)

        self.assertTrue(
            output.startswith(
                "<!-- Generated by scripts/generate-api.sh. Do not edit directly. -->\n\n"
                "# Swift API reference\n"
            )
        )
        self.assertEqual(output.count("### `"), 1)
        self.assertIn("public struct Wallet: Sendable {", output)
        self.assertEqual(output.count("Sendable"), 1)
        self.assertNotIn("SendableMetatype", output)
        self.assertIn("    /// Signs a value.", output)
        self.assertIn("    public func sign(_ value: String)", output)
        self.assertIn("    public func sign(_ value: Data)", output)
        self.assertNotIn("Parameter value", output)

    def test_renders_public_members_and_restricted_setters(self):
        values = [
            symbol(
                "access-fixture",
                "AccessFixture",
                ["final class AccessFixture"],
                "swift.class",
                "AccessFixture",
            ),
            symbol(
                "identifier",
                "AccessFixture.identifier",
                ["let identifier: ", "String"],
                "swift.property",
                "identifier",
                parent="access-fixture",
            ),
            symbol(
                "selected-wallet",
                "AccessFixture.selectedWallet",
                ["var selectedWallet: ", "String?", " { get set }"],
                "swift.property",
                "selectedWallet",
                parent="access-fixture",
            ),
            symbol(
                "attributed-operation",
                "attributedOperation()",
                ["@discardableResult ", "func attributedOperation() -> ", "Bool"],
                "swift.func",
                "attributedOperation",
            ),
        ]

        output = generate_api.render(
            generate_api.ordered_symbols(
                generate_api.public_symbols(graph(values)),
                config(
                    [
                        {"path": "AccessFixture"},
                        {"path": "attributedOperation()"},
                    ]
                ),
            )
        )

        self.assertIn("    public let identifier: String", output)
        self.assertIn(
            "    public internal(set) var selectedWallet: String? { get set }",
            output,
        )
        self.assertIn(
            "@discardableResult public func attributedOperation() -> Bool",
            output,
        )

    def test_split_client_fails_when_a_public_member_is_unassigned(self):
        split_config = config(
            [{"path": "Wallet"}],
            [{"path": "Wallet.sign(_:)", "id": "first-overload"}],
        )

        with self.assertRaisesRegex(
            generate_api.GenerationError, "Public symbols are unassigned"
        ):
            generate_api.ordered_symbols(self.symbols, split_config)

    def test_split_client_member_renders_as_its_own_entry(self):
        split_config = config(
            [{"path": "Wallet"}],
            [
                {"path": "Wallet.sign(_:)", "id": "first-overload"},
                {"path": "Wallet.sign(_:)", "id": "second-overload"},
            ],
        )

        output = generate_api.render(
            generate_api.ordered_symbols(self.symbols, split_config)
        )

        self.assertEqual(output.count("### `"), 3)
        self.assertNotIn("public struct Wallet {", output)

    def test_fails_when_a_configured_symbol_is_missing(self):
        with self.assertRaisesRegex(
            generate_api.GenerationError, "Configured symbol is missing"
        ):
            generate_api.ordered_symbols(
                self.symbols, config([{"path": "Missing"}])
            )

    def test_requires_ids_for_overloads_with_the_same_path(self):
        with self.assertRaisesRegex(
            generate_api.GenerationError, "ambiguous and requires an ID"
        ):
            generate_api.ordered_symbols(
                self.symbols, config([{"path": "Wallet.sign(_:)"}])
            )

    def test_recovers_raw_enum_headers_literals_and_unchecked_sendable(self):
        values = [
            symbol(
                "raw-status",
                "RawStatus",
                ["enum RawStatus"],
                "swift.enum",
                "RawStatus",
            ),
            symbol(
                "ready",
                "RawStatus.ready",
                ["case ready"],
                "swift.enum.case",
                "ready",
                parent="raw-status",
            ),
            symbol(
                "waiting",
                "RawStatus.waiting",
                ["case waiting"],
                "swift.enum.case",
                "waiting",
                parent="raw-status",
            ),
            symbol(
                "unsafe-wallet",
                "UnsafeWallet",
                ["final class UnsafeWallet"],
                "swift.class",
                "UnsafeWallet",
            ),
        ]
        symbols = generate_api.public_symbols(
            graph(
                values,
                [
                    {
                        "kind": "conformsTo",
                        "source": "unsafe-wallet",
                        "target": "sendable",
                        "targetFallback": "Swift.Sendable",
                    }
                ],
            )
        )

        output = generate_api.render(
            generate_api.ordered_symbols(
                symbols, config([{"path": "RawStatus"}, {"path": "UnsafeWallet"}])
            )
        )

        self.assertIn("public enum RawStatus: String, Sendable {", output)
        self.assertIn('    case ready = "ready-value"', output)
        self.assertIn('    case waiting = "waiting-value"', output)
        self.assertIn(
            "public final class UnsafeWallet: FixtureProtocol, @unchecked Sendable",
            output,
        )

    def test_resolves_same_module_conformance_target_identifier(self):
        values = [
            symbol(
                "fixture-protocol",
                "FixtureProtocol",
                ["protocol FixtureProtocol"],
                "swift.protocol",
                "FixtureProtocol",
            ),
            symbol(
                "same-module-conformer",
                "SameModuleConformer",
                ["struct SameModuleConformer"],
                "swift.struct",
                "SameModuleConformer",
            ),
        ]

        symbols = generate_api.public_symbols(
            graph(
                values,
                [
                    {
                        "kind": "conformsTo",
                        "source": "same-module-conformer",
                        "target": "fixture-protocol",
                    }
                ],
            )
        )

        conformer = next(
            symbol for symbol in symbols if symbol.identifier == "same-module-conformer"
        )
        self.assertEqual(conformer.conformances, ("FixtureProtocol",))

    def test_rejects_conditional_conformance(self):
        values = [
            symbol(
                "same-module-conformer",
                "SameModuleConformer",
                ["struct SameModuleConformer"],
                "swift.struct",
                "SameModuleConformer",
            )
        ]

        with self.assertRaisesRegex(
            generate_api.GenerationError, "Conditional public conformance is unsupported"
        ):
            generate_api.public_symbols(
                graph(
                    values,
                    [
                        {
                            "kind": "conformsTo",
                            "source": "same-module-conformer",
                            "target": "sendable",
                            "targetFallback": "Swift.Sendable",
                            "swiftConstraints": [
                                {"kind": "conformance", "lhs": "T", "rhs": "Sendable"}
                            ],
                        }
                    ],
                )
            )

    def test_rejects_multiple_enum_cases_in_one_source_declaration(self):
        values = [
            symbol(
                "unsupported-cases",
                "UnsupportedCases",
                ["enum UnsupportedCases"],
                "swift.enum",
                "UnsupportedCases",
            ),
            symbol(
                "first",
                "UnsupportedCases.first",
                ["case first"],
                "swift.enum.case",
                "first",
                parent="unsupported-cases",
            ),
        ]

        with self.assertRaisesRegex(
            generate_api.GenerationError, "Multiple enum cases per declaration are unsupported"
        ):
            generate_api.public_symbols(graph(values))

    def test_rejects_malformed_source_location(self):
        value, relationship = symbol(
            "raw-status",
            "RawStatus",
            ["enum RawStatus"],
            "swift.enum",
            "RawStatus",
        )
        value["location"]["position"]["character"] += 1

        with self.assertRaisesRegex(
            generate_api.GenerationError, "Source location does not point"
        ):
            generate_api.public_symbols(graph([(value, relationship)]))

    def test_rejects_generated_waas_source_locations(self):
        value, relationship = symbol(
            "generated",
            "GeneratedType",
            ["struct GeneratedType"],
            "swift.struct",
            "Wallet",
        )
        value["location"]["uri"] = (
            FIXTURE_PATH.parent / "Sources" / "OMSWallet" / "Generated" / "waas.gen.swift"
        ).resolve().as_uri()

        with self.assertRaisesRegex(
            generate_api.GenerationError, "Generated source exposed a public symbol"
        ):
            generate_api.public_symbols(graph([(value, relationship)]))


if __name__ == "__main__":
    unittest.main()
