// Generated by design-architect. Do not edit manually.
// Theme: OMS (oms)
// swiftlint:disable all

import SwiftUI

private extension Color {
    init(designHex hex: String) {
        let value = hex.trimmingCharacters(in: CharacterSet(charactersIn: "#"))
        let scanner = Scanner(string: value)
        var rgba: UInt64 = 0
        scanner.scanHexInt64(&rgba)

        let red: Double
        let green: Double
        let blue: Double
        let alpha: Double

        if value.count == 8 {
            red = Double((rgba >> 24) & 0xff) / 255
            green = Double((rgba >> 16) & 0xff) / 255
            blue = Double((rgba >> 8) & 0xff) / 255
            alpha = Double(rgba & 0xff) / 255
        } else {
            red = Double((rgba >> 16) & 0xff) / 255
            green = Double((rgba >> 8) & 0xff) / 255
            blue = Double(rgba & 0xff) / 255
            alpha = 1
        }

        self.init(.sRGB, red: red, green: green, blue: blue, opacity: alpha)
    }
}

public enum DesignTheme {
    public static let id = "oms"
    public static let name = "OMS"
    public static let description = "Light financial product theme for OMS dashboards."
}

public enum DesignTokens {
    public enum Color {
        public static let page = SwiftUI.Color(designHex: "#F6F6FC")
        public static let surface = SwiftUI.Color(designHex: "#FFFFFF")
        public static let secondarySurface = SwiftUI.Color(designHex: "#F6F6FC")
        public static let header = SwiftUI.Color(designHex: "#FFFFFF")
        public static let headerBorder = SwiftUI.Color(designHex: "#DFE3F0")
        public static let footer = SwiftUI.Color(designHex: "#FFFFFF")
        public static let primaryText = SwiftUI.Color(designHex: "#141635")
        public static let secondaryText = SwiftUI.Color(designHex: "#64708F")
        public static let placeholderText = SwiftUI.Color(designHex: "#929EBA")
        public static let border = SwiftUI.Color(designHex: "#C8CFE1")
        public static let focusRing = SwiftUI.Color(designHex: "#B78EEF")
        public static let brand = SwiftUI.Color(designHex: "#670DE5")
        public static let hover = SwiftUI.Color(designHex: "#F6F6FC")
        public static let primaryButton = SwiftUI.Color(designHex: "#090624")
        public static let primaryButtonText = SwiftUI.Color(designHex: "#FFFFFF")
        public static let secondaryButton = SwiftUI.Color(designHex: "#FFFFFF")
        public static let secondaryButtonText = SwiftUI.Color(designHex: "#090624")
        public static let selectedButton = SwiftUI.Color(designHex: "#EAE4F5")
        public static let selectedButtonText = SwiftUI.Color(designHex: "#500AB2")
        public static let danger = SwiftUI.Color(designHex: "#DC2626")
        public static let dangerSoft = SwiftUI.Color(designHex: "#FEF2F2")
        public static let dangerText = SwiftUI.Color(designHex: "#FFFFFF")
        public static let success = SwiftUI.Color(designHex: "#047857")
        public static let successSoft = SwiftUI.Color(designHex: "#ECFDF5")
        public static let warning = SwiftUI.Color(designHex: "#B45309")
        public static let warningSoft = SwiftUI.Color(designHex: "#FFF7ED")
        public static let info = SwiftUI.Color(designHex: "#500AB2")
        public static let infoSoft = SwiftUI.Color(designHex: "#F6F3FB")
    }

    public enum Typography {
        public static let family = "Fustat"
        public static let heading = Font.custom(family, size: 24).weight(.bold)
        public static let body = Font.custom(family, size: 16).weight(.medium)
        public static let caption = Font.custom(family, size: 14).weight(.medium)
        public static let subtle = Font.custom(family, size: 12).weight(.medium)
        public static let button = Font.custom(family, size: 14).weight(.bold)
    }

    public enum Spacing {
        public static let xsmall: CGFloat = 4
        public static let small: CGFloat = 8
        public static let medium: CGFloat = 12
        public static let large: CGFloat = 16
        public static let xlarge: CGFloat = 24
    }

    public enum Radius {
        public static let button: CGFloat = 12
        public static let buttonLarge: CGFloat = 12
        public static let input: CGFloat = 12
        public static let badge: CGFloat = 999
        public static let card: CGFloat = 24
    }

    public enum Stroke {
        public static let defaultWidth: CGFloat = 1
        public static let boxWidth: CGFloat = 1
        public static let labelWidth: CGFloat = 1
        public static let buttonWidth: CGFloat = 1
    }
}

public enum DesignButtonVariant: Sendable {
    case primary
    case secondary
    case selected
    case dangerPrimary
    case dangerSecondary
}

public enum DesignButtonSize: Sendable {
    case small
    case medium
    case large
}

public enum DesignBadgeVariant: Sendable {
    case info
    case neutral
    case success
    case warning
    case danger
}

public enum DesignTextVariant: Sendable {
    case title
    case body
    case caption
    case subtle
    case error
}

public struct DesignButtonStyle: ButtonStyle {
    private let variant: DesignButtonVariant
    private let size: DesignButtonSize
    private let fillsWidth: Bool

    public init(
        variant: DesignButtonVariant = .primary,
        size: DesignButtonSize = .medium,
        fillsWidth: Bool = false
    ) {
        self.variant = variant
        self.size = size
        self.fillsWidth = fillsWidth
    }

    public func makeBody(configuration: Configuration) -> some View {
        configuration.label
            .font(font)
            .lineLimit(1)
            .minimumScaleFactor(0.85)
            .padding(.horizontal, horizontalPadding)
            .frame(minHeight: height)
            .frame(maxWidth: fillsWidth ? .infinity : nil)
            .background(configuration.isPressed ? pressedBackground : background)
            .foregroundStyle(foreground)
            .overlay(
                RoundedRectangle(cornerRadius: cornerRadius)
                    .stroke(borderColor, lineWidth: borderWidth)
            )
            .clipShape(RoundedRectangle(cornerRadius: cornerRadius))
            .contentShape(RoundedRectangle(cornerRadius: cornerRadius))
    }

    private var font: Font {
        switch size {
        case .small: Font.custom(DesignTokens.Typography.family, size: 12).weight(.bold)
        case .medium: Font.custom(DesignTokens.Typography.family, size: 14).weight(.bold)
        case .large: Font.custom(DesignTokens.Typography.family, size: 16).weight(.bold)
        }
    }

    private var height: CGFloat {
        switch size {
        case .small: 30
        case .medium: 32
        case .large: 40
        }
    }

    private var horizontalPadding: CGFloat {
        switch size {
        case .small: 8
        case .medium: 12
        case .large: 12
        }
    }

    private var cornerRadius: CGFloat {
        switch size {
        case .large: DesignTokens.Radius.buttonLarge
        case .medium, .small: DesignTokens.Radius.button
        }
    }

    private var background: SwiftUI.Color {
        switch variant {
        case .primary: DesignTokens.Color.primaryButton
        case .secondary: DesignTokens.Color.secondaryButton
        case .selected: DesignTokens.Color.selectedButton
        case .dangerPrimary: DesignTokens.Color.danger
        case .dangerSecondary: DesignTokens.Color.dangerSoft
        }
    }

    private var pressedBackground: SwiftUI.Color {
        switch variant {
        case .primary, .secondary: DesignTokens.Color.hover
        case .selected: DesignTokens.Color.selectedButton
        case .dangerPrimary: DesignTokens.Color.danger
        case .dangerSecondary: DesignTokens.Color.dangerSoft
        }
    }

    private var foreground: SwiftUI.Color {
        switch variant {
        case .primary: DesignTokens.Color.primaryButtonText
        case .secondary: DesignTokens.Color.secondaryButtonText
        case .selected: DesignTokens.Color.selectedButtonText
        case .dangerPrimary: SwiftUI.Color.white
        case .dangerSecondary: DesignTokens.Color.dangerText
        }
    }

    private var borderColor: SwiftUI.Color {
        switch variant {
        case .primary, .dangerPrimary: SwiftUI.Color.clear
        case .secondary: DesignTokens.Color.border
        case .selected: DesignTokens.Color.selectedButton
        case .dangerSecondary: DesignTokens.Color.danger
        }
    }

    private var borderWidth: CGFloat {
        switch variant {
        case .primary, .dangerPrimary: 0
        case .secondary, .selected, .dangerSecondary: DesignTokens.Stroke.buttonWidth
        }
    }
}

public struct DesignIconButton: View {
    private let systemImage: String
    private let accessibilityLabel: String
    private let size: CGFloat
    private let action: () -> Void

    public init(
        systemImage: String,
        accessibilityLabel: String,
        size: CGFloat = 40,
        action: @escaping () -> Void
    ) {
        self.systemImage = systemImage
        self.accessibilityLabel = accessibilityLabel
        self.size = size
        self.action = action
    }

    public var body: some View {
        Button(action: action) {
            Image(systemName: systemImage)
                .font(.system(size: size * 0.38, weight: .semibold))
                .frame(width: size, height: size)
                .background(DesignTokens.Color.surface)
                .foregroundStyle(DesignTokens.Color.primaryText)
                .overlay(
                    RoundedRectangle(cornerRadius: DesignTokens.Radius.buttonLarge)
                        .stroke(DesignTokens.Color.border, lineWidth: DesignTokens.Stroke.buttonWidth)
                )
                .clipShape(RoundedRectangle(cornerRadius: DesignTokens.Radius.buttonLarge))
        }
        .buttonStyle(.plain)
        .accessibilityLabel(accessibilityLabel)
    }
}

public struct DesignText: View {
    private let text: String
    private let variant: DesignTextVariant

    public init(_ text: String, variant: DesignTextVariant = .body) {
        self.text = text
        self.variant = variant
    }

    public var body: some View {
        Text(text)
            .font(font)
            .foregroundStyle(color)
            .fixedSize(horizontal: false, vertical: true)
    }

    private var font: Font {
        switch variant {
        case .title: DesignTokens.Typography.heading
        case .body: DesignTokens.Typography.body
        case .caption: DesignTokens.Typography.caption
        case .subtle: DesignTokens.Typography.subtle
        case .error: DesignTokens.Typography.caption
        }
    }

    private var color: SwiftUI.Color {
        switch variant {
        case .title, .body: DesignTokens.Color.primaryText
        case .caption, .subtle: DesignTokens.Color.secondaryText
        case .error: DesignTokens.Color.danger
        }
    }
}

public struct DesignToggle: View {
    private let title: String
    @Binding private var isOn: Bool

    public init(_ title: String, isOn: Binding<Bool>) {
        self.title = title
        self._isOn = isOn
    }

    public var body: some View {
        Toggle(title, isOn: $isOn)
            .font(DesignTokens.Typography.caption)
            .foregroundStyle(DesignTokens.Color.primaryText)
            .tint(DesignTokens.Color.brand)
    }
}

public struct DesignBadge: View {
    private let text: String
    private let variant: DesignBadgeVariant

    public init(_ text: String, variant: DesignBadgeVariant = .neutral) {
        self.text = text
        self.variant = variant
    }

    public var body: some View {
        Text(text)
            .font(.custom(DesignTokens.Typography.family, size: 12).weight(.medium))
            .foregroundStyle(foregroundColor)
            .padding(.horizontal, 10)
            .padding(.vertical, 3)
            .background(backgroundColor)
            .overlay(
                Capsule()
                    .stroke(borderColor, lineWidth: DesignTokens.Stroke.labelWidth)
            )
            .clipShape(Capsule())
    }

    private var backgroundColor: SwiftUI.Color {
        switch variant {
        case .info: DesignTokens.Color.infoSoft
        case .neutral: DesignTokens.Color.secondarySurface
        case .success: DesignTokens.Color.successSoft
        case .warning: DesignTokens.Color.warningSoft
        case .danger: DesignTokens.Color.dangerSoft
        }
    }

    private var foregroundColor: SwiftUI.Color {
        switch variant {
        case .info: DesignTokens.Color.info
        case .neutral: DesignTokens.Color.primaryText
        case .success: DesignTokens.Color.success
        case .warning: DesignTokens.Color.warning
        case .danger: DesignTokens.Color.danger
        }
    }

    private var borderColor: SwiftUI.Color {
        switch variant {
        case .info: DesignTokens.Color.info
        case .neutral: DesignTokens.Color.border
        case .success: DesignTokens.Color.success
        case .warning: DesignTokens.Color.warning
        case .danger: DesignTokens.Color.danger
        }
    }
}

public struct DesignCard<Content: View>: View {
    private let content: () -> Content

    public init(@ViewBuilder content: @escaping () -> Content) {
        self.content = content
    }

    public var body: some View {
        VStack(alignment: .leading, spacing: DesignTokens.Spacing.large) {
            content()
        }
        .padding(16)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(DesignTokens.Color.surface)
        .overlay(
            RoundedRectangle(cornerRadius: DesignTokens.Radius.card)
                .stroke(DesignTokens.Color.headerBorder, lineWidth: DesignTokens.Stroke.boxWidth)
        )
        .clipShape(RoundedRectangle(cornerRadius: DesignTokens.Radius.card))
    }
}

public struct DesignTextField: View {
    private let title: String
    @Binding private var text: String
    private let isDestructive: Bool

    public init(_ title: String, text: Binding<String>, isDestructive: Bool = false) {
        self.title = title
        self._text = text
        self.isDestructive = isDestructive
    }

    public var body: some View {
        TextField(title, text: $text)
            .font(DesignTokens.Typography.caption)
            .foregroundStyle(DesignTokens.Color.primaryText)
            .padding(.horizontal, 12)
            .frame(minHeight: 40)
            .background(DesignTokens.Color.secondarySurface)
            .overlay(
                RoundedRectangle(cornerRadius: DesignTokens.Radius.input)
                    .stroke(isDestructive ? DesignTokens.Color.danger : DesignTokens.Color.border, lineWidth: DesignTokens.Stroke.buttonWidth)
            )
            .clipShape(RoundedRectangle(cornerRadius: DesignTokens.Radius.input))
    }
}
